/** 12-pixel icons drawn as the favicon is: one path per colour, a unit square per pixel. */

const PALETTE = {
	k: "#16130f",
	d: "#55514a",
	g: "#9a958a",
	w: "#ffffff",
	b: "#3a5a80",
	l: "#6f8fb5",
	y: "#e0b030",
	r: "#c8361e",
	n: "#3f8a3a",
} as const;
type Ink = keyof typeof PALETTE;
const isInk = (c: string): c is Ink => c in PALETTE;

export interface PixelPath {
	readonly fill: string;
	readonly d: string;
}

/** Each row's runs of one ink become one rectangle; `.` is clear. */
function pixelPaths(rows: readonly string[], palette: Readonly<Record<string, string>>): PixelPath[] {
	const byFill = new Map<string, string[]>();
	rows.forEach((row, y) => {
		for (let x = 0; x < row.length;) {
			const c = row.charAt(x);
			let end = x + 1;
			while (row.charAt(end) === c) end++;
			const fill = palette[c];
			if (fill !== undefined) {
				const runs = byFill.get(fill) ?? [];
				runs.push(`M${x} ${y}h${end - x}v1h-${end - x}z`);
				byFill.set(fill, runs);
			}
			x = end;
		}
	});
	return [...byFill].map(([fill, runs]) => ({ fill, d: runs.join("") }));
}

const ICONS = {
	tower: [
		"k....kk....k",
		"k.k..kk..k.k",
		"k.k.kyyk.k.k",
		"k.k..kk..k.k",
		"k....kk....k",
		".....kk.....",
		"....kddk....",
		"....kddk....",
		"...kd..dk...",
		"...kdkkdk...",
		"..kd....dk..",
		".kkkkkkkkkk.",
	],
	bolt: [
		"......kkkk..",
		".....kyyyk..",
		"....kyyyk...",
		"...kyyyk....",
		"..kyyyykkkk.",
		"..kkkkyyyyk.",
		"....kyyyyk..",
		"...kyyyk....",
		"..kyyk......",
		"..kyk.......",
		".kyk........",
		".kk.........",
	],
	mic: [
		"....kkkk....",
		"...kwwllk...",
		"...kwlllk...",
		"...klllbk...",
		"...klllbk...",
		".k.kllbbk.k.",
		".k.kbbbbk.k.",
		"..k.kkkk.k..",
		"...kk..kk...",
		".....kk.....",
		".....kk.....",
		"...kkkkkk...",
	],
	plus: [
		"............",
		"kkkkkkkkkkkk",
		"kbbbbbbbbbbk",
		"kbwwwbbbwbbk",
		"kbwbbbbbwbbk",
		"kbwwbbwwwwwk",
		"kbbbwbbbwbbk",
		"kbbbwbbbwbbk",
		"kbwwbbbbbbbk",
		"kbbbbbbbbbbk",
		"kkkkkkkkkkkk",
		"............",
	],
	handset: [
		"............",
		".kkk........",
		"kwwlk.......",
		"kwllk.......",
		"kllk........",
		".klk........",
		".kllk.......",
		"..klk...kkk.",
		"..kllkkkllk.",
		"...kllllllk.",
		"....kkkkkk..",
		"............",
	],
	wave: [
		"............",
		"......k.....",
		"....k.k.....",
		"..k.k.k.k...",
		"..k.kykyk.k.",
		"k.kykykykyk.",
		"kykykykykyk.",
		"..kykykyk...",
		"....kyk.....",
		"......k.....",
		"............",
		"............",
	],
	camera: [
		"............",
		"............",
		"kkkkkkkk....",
		"kddddddk..kk",
		"kdwwdddk.kdk",
		"kdwdddddkddk",
		"kddddddddddk",
		"kddddddk.kdk",
		"kddddddk..kk",
		"kkkkkkkk....",
		"............",
		"............",
	],
	wifi: [
		"............",
		"..bbbbbbbb..",
		".b........b.",
		"b..bbbbbb..b",
		"..b......b..",
		"....bbbb....",
		"...b....b...",
		"............",
		".....kk.....",
		".....kk.....",
		"............",
		"............",
	],
	globe: [
		"....kkkk....",
		"..kkbnbbkk..",
		".kbnnnbbbbk.",
		".knnnbbbnnk.",
		"kbnnbbbbnnbk",
		"kbbnbbbbbnbk",
		"kbbbbbnnbbbk",
		"kbbbbnnnnbbk",
		".kbbbnnnbbk.",
		".kbbbbnbbbk.",
		"..kkbbbbkk..",
		"....kkkk....",
	],
	laptop: [
		"............",
		".kkkkkkkkkk.",
		".kwllllllbk.",
		".kllllllllk.",
		".kllllllllk.",
		".kllllllbbk.",
		".kkkkkkkkkk.",
		"kddddddddddk",
		"kkkkkkkkkkkk",
		"............",
		"............",
		"............",
	],
	gear: [
		".....kk.....",
		"..k.kddk.k..",
		".kdkddddkdk.",
		"..kddkkddk..",
		".kddk..kddk.",
		"kdddk..kdddk",
		".kddk..kddk.",
		"..kddkkddk..",
		".kdkddddkdk.",
		"..k.kddk.k..",
		".....kk.....",
		"............",
	],
	tape: [
		"............",
		"............",
		"............",
		".kkk....kkk.",
		"kwwwk..kwwwk",
		"kw.wk..kw.wk",
		"kwwwkkkkwwwk",
		".kkkkkkkkkk.",
		"............",
		"............",
		"............",
		"............",
	],
	bubble: [
		"............",
		".kkkkkkkkkk.",
		"kllllllllllk",
		"kllllllllllk",
		"klwwlwwlwwlk",
		"kllllllllllk",
		"kllllllllllk",
		".kkkllkkkkk.",
		"...klk......",
		"...kk.......",
		"............",
		"............",
	],
	shop: [
		"............",
		"kkkkkkkkkkkk",
		"krwrwrwrwrwk",
		"krwrwrwrwrwk",
		"kkkkkkkkkkkk",
		".kwwwwwwwwk.",
		".kwkkkwwwwk.",
		".kwkbkwwwwk.",
		".kwkbkwkkwk.",
		".kwkbkwkkwk.",
		"kkkkkkkkkkkk",
		"............",
	],
	satellite: [
		"............",
		"kkkk........",
		"kblbk.......",
		"kblblk......",
		".kblbkk.....",
		"..kbkddk....",
		"....kddddk..",
		".....kddkbk.",
		"......kkblbk",
		".......kblbk",
		"........kkkk",
		"............",
	],
	badge: [
		"............",
		"kkkkkkkkkkkk",
		"kwwwwwwwwwwk",
		"kwkkkkwwwwwk",
		"kwkyykwddddk",
		"kwkyykwwwwwk",
		"kwkkkkwddwwk",
		"kwwwwwwwwwwk",
		"kkkkkkkkkkkk",
		"............",
		"............",
		"............",
	],
	shield: [
		".kkkkkkkkkk.",
		".knnnnnnwwk.",
		".knnnnnnnwk.",
		".knnnnnwnnk.",
		".knnnnwwnnk.",
		".knwnwwnnnk.",
		".knwwwnnnnk.",
		"..knwnnnnk..",
		"..knnnnnnk..",
		"...knnnnk...",
		"....knnk....",
		".....kk.....",
	],
	sim: [
		"..kkkkkkk...",
		"..kwwwwwwk..",
		"..kwyyyywwk.",
		"..kwykkywwk.",
		"..kwyyyywwk.",
		"..kwykkywwk.",
		"..kwyyyywwk.",
		"..kwwwwwwwk.",
		"..kwwwwwwwk.",
		"..kkkkkkkkk.",
		"............",
		"............",
	],
	arrows: [
		"............",
		"......k.....",
		"......kk....",
		"kkkkkkkyk...",
		"kyyyyyyyyk..",
		"kkkkkkkyk...",
		"...k..kk....",
		"..kk..k.....",
		".kbkkkkkkkk.",
		"kbbbbbbbbbk.",
		".kbkkkkkkkk.",
		"..kk........",
	],
	watch: [
		"....kkkk....",
		"....kddk....",
		"...kkkkkk...",
		"..kddddddk..",
		"..kdbbbbdkk.",
		"..kdbwwbdkk.",
		"..kdbbbbdk..",
		"..kddddddk..",
		"...kkkkkk...",
		"....kddk....",
		"....kkkk....",
		"............",
	],
	power: [
		".....kk.....",
		"..k..nn..k..",
		".knk.nn.knk.",
		"knnk.nn.knnk",
		"knk..nn..knk",
		"kn...kk...nk",
		"kn........nk",
		"knk......knk",
		".knk....knk.",
		"..knnnnnnk..",
		"...kkkkkk...",
		"............",
	],
	toggle: [
		"............",
		"............",
		"............",
		"..kkkkkkkk..",
		".knnnnkwwwk.",
		"knnnnkwwwwwk",
		"knnnnkwwwwwk",
		".knnnnkwwwk.",
		"..kkkkkkkk..",
		"............",
		"............",
		"............",
	],
	forward: [
		"............",
		".kk.........",
		"kwlk.....k..",
		"kllk.....kk.",
		"klk..kkkkkyk",
		".kk..kyyyyyk",
		".klk.kkkkkyk",
		"..klk....kk.",
		"...kllkk.k..",
		"....kllllk..",
		".....kkkk...",
		"............",
	],
	slash: [
		"..........rr",
		".........rr.",
		"........rr..",
		".kkk...rrkk.",
		"kwwwk.rrwwwk",
		"kw.wkrrkw.wk",
		"kwwwrrkkwwwk",
		".kkrrkkkkkk.",
		"..rr........",
		".rr.........",
		"rr..........",
		"............",
	],
	hash: [
		"............",
		"...kk..kk...",
		"...kk..kk...",
		".kkkkkkkkkk.",
		".kkkkkkkkkk.",
		"...kk..kk...",
		"...kk..kk...",
		".kkkkkkkkkk.",
		".kkkkkkkkkk.",
		"...kk..kk...",
		"...kk..kk...",
		"............",
	],
	lock: [
		"....kkkk....",
		"...k....k...",
		"..k......k..",
		"..k......k..",
		".kkkkkkkkkk.",
		".kyyyyyyyyk.",
		".kyyykkyyyk.",
		".kyyykkyyyk.",
		".kyyyykyyyk.",
		".kyyyyyyyyk.",
		".kkkkkkkkkk.",
		"............",
	],
	house: [
		".....kk.....",
		"....kbbk....",
		"...kbbbbk...",
		"..kbbbbbbk..",
		".kbbbbbbbbk.",
		"kkkkkkkkkkkk",
		".kwwwwwwwwk.",
		".kw.bbbb.wk.",
		".kwb....bwk.",
		".kww.bb.wwk.",
		".kwwwkkwwwk.",
		".kkkkkkkkkk.",
	],
	pin: [
		"....kkkk....",
		"...krrrrk...",
		"..krrwwrrk..",
		"..krwwwwrk..",
		"..krrwwrrk..",
		"...krrrrk...",
		"...krrrrk...",
		"....krrk....",
		"....krrk....",
		".....kk.....",
		"..gggggggg..",
		"............",
	],
	tag: [
		"............",
		"....kkkkkkkk",
		"...kyyyyyyyk",
		"..kyykyyyyyk",
		".kyyyyyyyyyk",
		"kyyyyyyyyyyk",
		".kyyyyyyyyyk",
		"..kyyyyyyyyk",
		"...kyyyyyyyk",
		"....kkkkkkkk",
		"............",
		"............",
	],
	apn: [
		"............",
		"............",
		"kkkkkkkkkkkk",
		"kbbbbbbbbbbk",
		"kbwbwwbwbbwk",
		"kwbwwbwwwbwk",
		"kwwwwwbwbwwk",
		"kwbwwbbwbbwk",
		"kbbbbbbbbbbk",
		"kkkkkkkkkkkk",
		"............",
		"............",
	],
	dual: [
		"............",
		"............",
		"kk.kk..kkkkk",
		"kk.kk..kk...",
		"kk.kk..kk...",
		"kkkkk..kkkkk",
		"...kk..kk.kk",
		"...kk..kk.kk",
		"...kk..kkkkk",
		"............",
		"............",
		"............",
	],
	envelope: [
		"............",
		"............",
		"kkkkkkkkkkkk",
		"kkwwwwwwwwkk",
		"kwkwwwwwwkwk",
		"kwwkwwwwkwwk",
		"kwwwkkkkwwwk",
		"kwwwwwwwwwwk",
		"kwwwwwwwwwwk",
		"kkkkkkkkkkkk",
		"............",
		"............",
	],
	letters: [
		"............",
		"............",
		"kkkkkkkkkkkk",
		"kllllllllllk",
		"kwlwlllwwwlk",
		"kwlwlllwllwk",
		"kwwwllwlllwk",
		"klwlllwlwwlk",
		"klwlllwwwwlk",
		"kllllllllllk",
		"kkkkkkkkkkkk",
		"............",
	],
} as const satisfies Record<string, readonly string[]>;
export type IconName = keyof typeof ICONS;

export const ICON_SIZE = 12;

const drawn = (rows: readonly string[]): PixelPath[] =>
	pixelPaths(rows, Object.fromEntries([...new Set(rows.join(""))].filter(isInk).map((c) => [c, PALETTE[c]])));

const cache = new Map<IconName, readonly PixelPath[]>();

export function iconPaths(name: IconName): readonly PixelPath[] {
	let paths = cache.get(name);
	if (!paths) cache.set(name, (paths = drawn(ICONS[name])));
	return paths;
}

const svgUrl = (paths: readonly PixelPath[], size: number): string =>
	`url("data:image/svg+xml,${encodeURIComponent(
		`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges">${paths
			.map((p) => `<path fill="${p.fill}" d="${p.d}"/>`)
			.join("")}</svg>`,
	)}")`;

const urls = new Map<IconName, string>();

/** An icon as a CSS image: a matrix cell paints it rather than holding an SVG of its own. */
export function iconUrl(name: IconName): string {
	let url = urls.get(name);
	if (!url) urls.set(name, (url = svgUrl(iconPaths(name), ICON_SIZE)));
	return url;
}

/** A workstation backdrop: the desktop's blue, raised and sunk a pixel every other pixel. */
export const STIPPLE_URL = svgUrl(
	pixelPaths(["baaa", "acaa", "aaba", "aaac"], { a: "#4b6785", b: "#6a88aa", c: "#3a5270" }),
	4,
);
