/** Apple internal device codename -> marketing name.
 *  Derived from the public model tables; bundles name their override files by codename. */
export const DEVICE_CODENAMES: Record<string, { name: string; ids: string }> = {
  "D10": { name: "iPhone 7", ids: "iPhone9,1" },
  "D101": { name: "iPhone 7", ids: "iPhone9,3" },
  "D11": { name: "iPhone 7 Plus", ids: "iPhone9,2" },
  "D111": { name: "iPhone 7 Plus", ids: "iPhone9,4" },
  "D16": { name: "iPhone 13 mini", ids: "iPhone14,4" },
  "D17": { name: "iPhone 13", ids: "iPhone14,5" },
  "D20": { name: "iPhone 8", ids: "iPhone10,1" },
  "D201": { name: "iPhone 8", ids: "iPhone10,4" },
  "D21": { name: "iPhone 8 Plus", ids: "iPhone10,2" },
  "D211": { name: "iPhone 8 Plus", ids: "iPhone10,5" },
  "D22": { name: "iPhone X", ids: "iPhone10,3" },
  "D221": { name: "iPhone X", ids: "iPhone10,6" },
  "D23": { name: "iPhone Air", ids: "iPhone18,4" },
  "D27": { name: "iPhone 14", ids: "iPhone14,7" },
  "D28": { name: "iPhone 14 Plus", ids: "iPhone14,8" },
  "D321": { name: "iPhone XS", ids: "iPhone11,2" },
  "D331": { name: "iPhone XS Max", ids: "iPhone11,4" },
  "D331p": { name: "iPhone XS Max", ids: "iPhone11,6" },
  "D37": { name: "iPhone 15", ids: "iPhone15,4" },
  "D38": { name: "iPhone 15 Plus", ids: "iPhone15,5" },
  "D421": { name: "iPhone 11 Pro", ids: "iPhone12,3" },
  "D431": { name: "iPhone 11 Pro Max", ids: "iPhone12,5" },
  "D47": { name: "iPhone 16", ids: "iPhone17,3" },
  "D48": { name: "iPhone 16 Plus", ids: "iPhone17,4" },
  "D49": { name: "iPhone SE (3rd generation)", ids: "iPhone14,6" },
  "D52g": { name: "iPhone 12 mini", ids: "iPhone13,1" },
  "D53g": { name: "iPhone 12", ids: "iPhone13,2" },
  "D53p": { name: "iPhone 12 Pro", ids: "iPhone13,3" },
  "D54p": { name: "iPhone 12 Pro Max", ids: "iPhone13,4" },
  "D63": { name: "iPhone 13 Pro", ids: "iPhone14,2" },
  "D64": { name: "iPhone 13 Pro Max", ids: "iPhone14,3" },
  "D73": { name: "iPhone 14 Pro", ids: "iPhone15,2" },
  "D74": { name: "iPhone 14 Pro Max", ids: "iPhone15,3" },
  "D79": { name: "iPhone SE (2nd generation)", ids: "iPhone12,8" },
  "D83": { name: "iPhone 15 Pro", ids: "iPhone16,1" },
  "D84": { name: "iPhone 15 Pro Max", ids: "iPhone16,2" },
  "D93": { name: "iPhone 16 Pro", ids: "iPhone17,1" },
  "D94": { name: "iPhone 16 Pro Max", ids: "iPhone17,2" },
  "J105a": { name: "Apple TV 4K", ids: "AppleTV6,2" },
  "J42d": { name: "Apple TV HD", ids: "AppleTV5,3" },
  "J71": { name: "iPad Air", ids: "iPad4,1" },
  "J72": { name: "iPad Air", ids: "iPad4,2" },
  "J73": { name: "iPad Air", ids: "iPad4,3" },
  "J81": { name: "iPad Air 2", ids: "iPad5,3" },
  "J82": { name: "iPad Air 2", ids: "iPad5,4" },
  "J85": { name: "iPad mini 2", ids: "iPad4,4" },
  "J85m": { name: "iPad mini 3", ids: "iPad4,7" },
  "J86": { name: "iPad mini 2", ids: "iPad4,5" },
  "J86m": { name: "iPad mini 3", ids: "iPad4,8" },
  "J87": { name: "iPad mini 2", ids: "iPad4,6" },
  "J87m": { name: "iPad mini 3", ids: "iPad4,9" },
  "J96": { name: "iPad mini 4", ids: "iPad5,1" },
  "J97": { name: "iPad mini 4", ids: "iPad5,2" },
  "K48": { name: "iPad", ids: "iPad1,1" },
  "K93": { name: "iPad 2", ids: "iPad2,1" },
  "K93A": { name: "iPad 2", ids: "iPad2,4" },
  "K94": { name: "iPad 2", ids: "iPad2,2" },
  "K95": { name: "iPad 2", ids: "iPad2,3" },
  "M68": { name: "iPhone", ids: "iPhone1,1" },
  "N104": { name: "iPhone 11", ids: "iPhone12,1" },
  "N111b": { name: "Apple Watch Series 3", ids: "Watch3,2" },
  "N111s": { name: "Apple Watch Series 3", ids: "Watch3,1" },
  "N121b": { name: "Apple Watch Series 3", ids: "Watch3,4" },
  "N121s": { name: "Apple Watch Series 3", ids: "Watch3,3" },
  "N131b": { name: "Apple Watch Series 4", ids: "Watch4,2" },
  "N131s": { name: "Apple Watch Series 4", ids: "Watch4,1" },
  "N140b": { name: "Apple Watch SE", ids: "Watch5,10" },
  "N140s": { name: "Apple Watch SE", ids: "Watch5,9" },
  "N141b": { name: "Apple Watch Series 4", ids: "Watch4,4" },
  "N141s": { name: "Apple Watch Series 4", ids: "Watch4,3" },
  "N142b": { name: "Apple Watch SE", ids: "Watch5,12" },
  "N142s": { name: "Apple Watch SE", ids: "Watch5,11" },
  "N143b": { name: "Apple Watch SE 2", ids: "Watch6,11" },
  "N143s": { name: "Apple Watch SE 2", ids: "Watch6,10" },
  "N144b": { name: "Apple Watch Series 5", ids: "Watch5,2" },
  "N144s": { name: "Apple Watch Series 5", ids: "Watch5,1" },
  "N146b": { name: "Apple Watch Series 5", ids: "Watch5,4" },
  "N146s": { name: "Apple Watch Series 5", ids: "Watch5,3" },
  "N149b": { name: "Apple Watch SE 2", ids: "Watch6,13" },
  "N149s": { name: "Apple Watch SE 2", ids: "Watch6,12" },
  "N157b": { name: "Apple Watch Series 6", ids: "Watch6,2" },
  "N157s": { name: "Apple Watch Series 6", ids: "Watch6,1" },
  "N158b": { name: "Apple Watch Series 6", ids: "Watch6,4" },
  "N158s": { name: "Apple Watch Series 6", ids: "Watch6,3" },
  "N187b": { name: "Apple Watch Series 7", ids: "Watch6,7" },
  "N187s": { name: "Apple Watch Series 7", ids: "Watch6,6" },
  "N188b": { name: "Apple Watch Series 7", ids: "Watch6,9" },
  "N188s": { name: "Apple Watch Series 7", ids: "Watch6,8" },
  "N197b": { name: "Apple Watch Series 8", ids: "Watch6,15" },
  "N197s": { name: "Apple Watch Series 8", ids: "Watch6,14" },
  "N198b": { name: "Apple Watch Series 8", ids: "Watch6,17" },
  "N198s": { name: "Apple Watch Series 8", ids: "Watch6,16" },
  "N199": { name: "Apple Watch Ultra", ids: "Watch6,18" },
  "N207b": { name: "Apple Watch Series 9", ids: "Watch7,2" },
  "N207s": { name: "Apple Watch Series 9", ids: "Watch7,1" },
  "N208b": { name: "Apple Watch Series 9", ids: "Watch7,4" },
  "N208s": { name: "Apple Watch Series 9", ids: "Watch7,3" },
  "N210": { name: "Apple Watch Ultra 2", ids: "Watch7,5" },
  "N217b": { name: "Apple Watch Series 10", ids: "Watch7,9" },
  "N217s": { name: "Apple Watch Series 10", ids: "Watch7,8" },
  "N218b": { name: "Apple Watch Series 10", ids: "Watch7,11" },
  "N218s": { name: "Apple Watch Series 10", ids: "Watch7,10" },
  "N227b": { name: "Apple Watch Series 11", ids: "Watch7,18" },
  "N227s": { name: "Apple Watch Series 11", ids: "Watch7,17" },
  "N228b": { name: "Apple Watch Series 11", ids: "Watch7,20" },
  "N228s": { name: "Apple Watch Series 11", ids: "Watch7,19" },
  "N230": { name: "Apple Watch Ultra 3", ids: "Watch7,12" },
  "N243b": { name: "Apple Watch SE 3", ids: "Watch7,14" },
  "N243s": { name: "Apple Watch SE 3", ids: "Watch7,13" },
  "N244b": { name: "Apple Watch SE 3", ids: "Watch7,16" },
  "N244s": { name: "Apple Watch SE 3", ids: "Watch7,15" },
  "N27d": { name: "Apple Watch Series 1", ids: "Watch2,6" },
  "N28d": { name: "Apple Watch Series 1", ids: "Watch2,7" },
  "N301": { name: "Apple Vision Pro", ids: "RealityDevice14,1" },
  "N41": { name: "iPhone 5", ids: "iPhone5,1" },
  "N42": { name: "iPhone 5", ids: "iPhone5,2" },
  "N48": { name: "iPhone 5c", ids: "iPhone5,3" },
  "N49": { name: "iPhone 5c", ids: "iPhone5,4" },
  "N51": { name: "iPhone 5s", ids: "iPhone6,1" },
  "N53": { name: "iPhone 5s", ids: "iPhone6,2" },
  "N56": { name: "iPhone 6 Plus", ids: "iPhone7,1" },
  "N61": { name: "iPhone 6", ids: "iPhone7,2" },
  "N66": { name: "iPhone 6s Plus", ids: "iPhone8,2" },
  "N69": { name: "iPhone SE", ids: "iPhone8,4" },
  "N71": { name: "iPhone 6s", ids: "iPhone8,1" },
  "N74": { name: "Apple Watch Series 2", ids: "Watch2,3" },
  "N75": { name: "Apple Watch Series 2", ids: "Watch2,4" },
  "N82": { name: "iPhone 3G", ids: "iPhone1,2" },
  "N841": { name: "iPhone XR", ids: "iPhone11,8" },
  "N88": { name: "iPhone 3GS", ids: "iPhone2,1" },
  "N90": { name: "iPhone 4", ids: "iPhone3,1" },
  "N90B": { name: "iPhone 4", ids: "iPhone3,2" },
  "N92": { name: "iPhone 4", ids: "iPhone3,3" },
  "N94": { name: "iPhone 4S", ids: "iPhone4,1" },
  "P105": { name: "iPad mini", ids: "iPad2,5" },
  "P106": { name: "iPad mini", ids: "iPad2,6" },
  "P107": { name: "iPad mini", ids: "iPad2,7" },
  "V159": { name: "iPhone 17e", ids: "iPhone18,5" },
  "V53": { name: "iPhone 17 Pro", ids: "iPhone18,1" },
  "V54": { name: "iPhone 17 Pro Max", ids: "iPhone18,2" },
  "V57": { name: "iPhone 17", ids: "iPhone18,3" },
  "V59": { name: "iPhone 16e", ids: "iPhone17,5" },
  "mvno1": { name: "MVNO override set (not a device)", ids: "" },
};

/** Split an `overrides_D63_D64_D16_D17` style stem into decorated device entries. */
export function describeDevices(stem: string): Array<{ code: string; name?: string; ids?: string }> {
  // Own properties only: a codename such as "constructor" must not resolve
  // through Object.prototype and invent a device.
  const lookup = (code: string) =>
    Object.hasOwn(DEVICE_CODENAMES, code) ? DEVICE_CODENAMES[code] : undefined;
  return stem.split("_").filter(Boolean).map((code) => {
    const hit = lookup(code) ?? lookup(code.replace(/[a-z]$/, ""));
    return hit ? { code, name: hit.name, ids: hit.ids } : { code };
  });
}
