/**
 * IMS (VoLTE / Wi-Fi Calling) preference registry: every key the IMS stack
 * registers under `IMSConfig.<Section>`, with its type and compiled-in default.
 * Also the legacy key renames, the enum-typed keys' allowed values and the
 * default call end-reason maps.
 *
 * Table recovered by emulating `ImsDefaultPrefs::addDefaultPrefs()` in the iOS 27.0
 * (24A437) dyld cache. A default is what the stack uses when the bundle omits the key.
 */

// libIPTelephony.dylib: ImsDefaultPrefs::addDefaultPrefs (add{Bool,Int,String,InterpolatedString,Dict,Array,Enum}Key)

/** b boolean, i integer, s string, x string with ${VAR} / $var placeholders, e enum (string), d dict, a array (comma list default). */
export type ImsTypeCode = "b" | "i" | "s" | "x" | "e" | "d" | "a";
type Row = readonly [key: string, type: ImsTypeCode, dflt?: string | number | boolean | null, note?: string];

export interface ImsSetting {
  key: string;
  /** Registry section, e.g. "Signaling" or "Signaling/SipTimers" (bundle path IMSConfig.Signaling.SipTimers). */
  section: string;
  type: ImsTypeCode;
  /** Compiled-in value used when the key is absent. Undefined for dicts. */
  default?: string | number | boolean;
  note?: string;
  /** Allowed values of an enum key, in declaration order. */
  values?: readonly string[];
  /** Set when the looked-up key is a legacy name that the stack still accepts. */
  renamedFrom?: string;
}

/** Allowed values of the enum-typed keys, in declaration order ('' = off / unset). */
export const IMS_ENUMS: Readonly<Record<string, readonly string[]>> = {
  AccessBarringType: ["SSAC", "ACB", "Both", "None"],
  AccessNetworkRefreshMethod: ["", "INVITE", "UPDATE"],
  CountryOfOriginationFormat: ["NONE", "PIDF", "PANI", "BOTH"],
  LocationForShortCodeCalls: ["NONE", "LATLONG", "CIVIC", "BOTH"],
  EmergencyPreferredIdentity: ["IMSI", "IMEI"],
  PIDFGeoPrivShape: ["Circle", "Ellipsoid"],
  Preconditions: ["None", "Supported", "SupportedOptional", "SupportedButMandatory", "Required"],
  VerstatFeatureCapability: ["Disabled", "Dynamic", "Enabled"],
  SpamHeaderFeatureCapability: ["Disabled", "Dynamic", "Enabled"],
  LinkMonitorPreference: ["", "RTP", "RTCP"],
};

/** Legacy key -> current key. Old names are still accepted.
 *  libIPTelephony.dylib: ImsDefaultPrefs::isKeyRenamed */
export const IMS_RENAMES: Readonly<Record<string, string>> = {
  CallSetupPingTimer: "CallSetupPingTimerMilliseconds",
  CountryOfOriginationForWifi: "CountryOfOriginationFormat",
  EmergencyLocationLookupTimeout: "EmergencyLocationLookupTimeoutSeconds",
  InternalIgnoreReregistrationErrorCodes: "IgnoreReregistrationErrorCodes",
  LocalQoSTimeoutMO: "LocalQoSTimeoutMOSeconds",
  LocalQoSTimeoutMT: "LocalQoSTimeoutMTSeconds",
  MinSessionExpires: "MinSessionExpiresSeconds",
  NetworkTerminationRetryInterval: "NetworkTerminationRetryIntervalSeconds",
  PdnBringupTimer: "PdnBringupTimerSeconds",
  PreconditionUpdateDelayTimer: "PreconditionUpdateDelayTimerMilliseconds",
  RegSubscriptionExpiration: "RegSubscriptionExpirationSeconds",
  RegistrationExpiration: "RegistrationExpirationSeconds",
  RegistrationRetryBaseTime: "RegistrationRetryBaseTimeSeconds",
  RegistrationRetryMaxTime: "RegistrationRetryMaxTimeSeconds",
  RingbackTimer: "RingbackTimerSeconds",
  RingingTimer: "RingingTimerSeconds",
  SessionExpires: "SessionExpiresSeconds",
  TcpIdleTimeout: "TcpIdleTimeoutSeconds",
  UssdResponseTimeout: "UssdResponseTimeoutMilliseconds",
  WaitForRingingTimerMO: "WaitForRingingTimerMOSeconds",
  WaitForRingingTimerMT: "WaitForRingingTimerMTSeconds",
  SipTimerA: "A",
  SipTimerB: "B",
  SipTimerC: "C",
  SipTimerD: "D",
  SipTimerE: "E",
  SipTimerF: "F",
  SipTimerG: "G",
  SipTimerH: "H",
  SipTimerI: "I",
  SipTimerJ: "J",
  SipTimerT1: "T1",
  SipTimerT2: "T2",
  SipTimerT4: "T4",
  "200Retransmit": "200RetransmitTimer",
  AckRetransmit: "AckRetransmitTimer",
  DTMFDigitDuration: "DTMFDigitDurationMilliseconds",
  DTMFInterDigitInterval: "DTMFInterDigitIntervalMilliseconds",
  HoldHeartbeatInterval: "HoldHeartbeatIntervalSeconds",
  InactivityTimerRTCP: "InactivityTimerRTCPSeconds",
  InactivityTimerRTPRTCP: "InactivityTimerRTPSeconds",
  LocalRTCPReportInterval: "LocalRTCPReportIntervalSeconds",
  MaxRed: "MaxRedundancy",
  RTCPInterval: "RTCPIntervalSeconds",
  ConferenceParticipantJoinTimeout: "ConferenceParticipantJoinTimeoutMilliseconds",
  ConferenceWaitForHoldTimeout: "ConferenceWaitForHoldTimeoutMilliseconds",
  RegistrationExpirationCushion: "RegistrationExpirationCushionSeconds",
  RegistrationRefreshCushionCap: "RegistrationRefreshCushionCapSeconds",
  RegistrationThrottlingCushionCap: "RegistrationThrottlingCushionCapSeconds",
  ShutdownWaitTime: "ShutdownWaitTimeSeconds",
  TTYReinviteTimeout: "TTYReinviteTimeoutMilliseconds",
};

/** The registry, by section. */
const SECTIONS: Readonly<Record<string, readonly Row[]>> = {
  "Signaling": [
    ["AcceptContactParams", "s", "", "Accept-Contact header parameters added to outgoing requests (e.g. \"require;explicit\")"],
    ["AcceptedSmsContentTypes", "s", "application/vnd.3gpp.sms,application/vnd.3gpp2.sms"],
    ["AccessBarringType", "e", "SSAC", "Which access-barring scheme gates IMS attempts: SSAC (service-specific), ACB, Both, None."],
    ["AccessNetworkRefreshMethod", "e", "", "SIP method used to refresh P-Access-Network-Info mid-call (INVITE or UPDATE; empty=off)"],
    ["AccessNetworkRefreshDelayMilliseconds", "i", 0, "Delay before sending the access-network-info refresh after a RAT/cell change."],
    ["AccessNetworkRefreshInHeldCalls", "b", true],
    ["AddAccessNetworkInfoToInsecureMessages", "b", false, "Include P-Access-Network-Info even on messages sent outside the IPsec SA."],
    ["AddConferenceParticipantsToInvite", "b", false, "Put the participant list (resource-list) in the conference-creation INVITE."],
    ["AddContentDispositionInPIDF", "b", true],
    ["AdditionalContactParams", "d", null, "Extra Contact header parameters (feature tags). Keyed by \"METHOD[,METHOD][:*][qualifier]\"; qualifiers include primary, wifi and emergency numbers."],
    ["AddQosOptionsToSockets", "b", true, "Mark SIP sockets with QoS/DSCP options."],
    ["AdditionalHeaders", "d", null, "Extra SIP headers appended to matching requests. Keyed by \"METHOD[qualifiers]\", e.g. INVITE[wifi,911]."],
    ["AdditionalFeatureTags", "d", null, "Extra feature tags advertised per service. Keyed by service (voice, sms, ...), then feature tag -> value."],
    ["AddGeolocationSupportedHeader", "b", false, "Add Supported: geolocation header."],
    ["AddRoutableLocalAddressHeader", "b", false, "Add a header carrying the UE's routable local address."],
    ["AddSipInstanceForWifi", "b", true],
    ["AllowAnonymousEmergencyCalls", "b", true, "Permit unauthenticated (anonymous/no-SIM) IMS emergency calls."],
    ["AllowEmergencyRetryForIPSec", "b", false, "Retry emergency registration/call when IPsec setup fails."],
    ["AllowAnonymousEmergencyCallsWhileRoaming", "b", true],
    ["AllowDisabledMode", "b", true],
    ["AllowEarlyRegistrationRefresh", "b", true],
    ["AllowInvalidTimestampInPCNI", "b", false],
    ["AllowPCNIInAirplaneMode", "b", true, "Allow P-Cellular-Network-Info to be sent while in airplane mode (Wi-Fi calling)"],
    ["AllowLimitedAccessModeRegistration", "b", false, "Allow IMS registration in limited-access (restricted) mode."],
    ["AllowMultipleAddressesPerProxy", "b", true],
    ["AllowRemoteHoldForUnconfirmedCalls", "b", false, "Accept remote hold before the call is confirmed (early dialog)"],
    ["AllowIncomingCallsDuringEmergencyCall", "b", false],
    ["AllowOutgoingCallsDuringEmergencyCall", "b", false],
    ["AllowPhoneContextInEmergencyUri", "b", true, "Allow ;phone-context in emergency Request-URI."],
    ["AllowTelUriInReferTo", "b", false],
    ["AllowResponsesOverDifferentTransport", "b", true, "Accept SIP responses arriving on a different transport than the request."],
    ["AllowRegistrationCanceledState", "b", true, "Allow registration state machine to enter 'canceled' state."],
    ["AllowSimultaneousCallsWhileUnregistered", "b", true, "Allow a second call while IMS is not registered."],
    ["AddEmergencyContactParamInInvite", "b", false, "Add the emergency (sos) Contact parameter in emergency INVITE."],
    ["AlwaysAddPrivacyHeader", "b", false, "Always add a Privacy header to outgoing requests."],
    ["AddPEmergencyInfoHeaderToEmergencyInviteOnWifi", "b", false, "Add P-Emergency-Info header to emergency INVITE over Wi-Fi."],
    ["KeepThrottleRegAfterTerminationWhileOutOfService", "b", true, "Keep registration throttling after termination while out of service."],
    ["AlwaysAddSipInstance", "b", false, "Always include +sip.instance (IMEI-based instance id) in Contact."],
    ["AcceptMsgFromNonProxy", "b", false],
    ["AlwaysAddSipInstanceToSubscribeRequest", "b", false, "Include +sip.instance also in SUBSCRIBE Contact."],
    ["RedialOverLteIfEpsFallbackCallFailed", "b", false, "Redial on LTE when an EPS-fallback (NR->LTE) call fails."],
    ["AlwaysAddTextService", "b", true, "Always advertise the text (RTT) media service."],
    ["CompressIPv6Addresses", "b", true],
    ["AlwaysEmergencyRegister", "b", true, "Always perform a dedicated emergency registration before an emergency call."],
    ["SkipEmergRegUnderSameTransport", "b", false, "Skip emergency registration if the normal registration is on the same transport."],
    ["AlwaysPrack18x", "b", false, "Always send PRACK for reliable 18x provisional responses."],
    ["AlwaysResetProxyList", "b", false],
    ["AlwaysSendSessionProgress", "b", false, "Always send 183 Session Progress on incoming calls."],
    ["AlwaysSendTryingResponse", "b", false, "Always send 100 Trying for incoming INVITE."],
    ["AlwaysSetPhoneContext", "b", false, "Always set ;phone-context on tel/sip URIs."],
    ["AlwaysAddGeolocationForEmergencyCalls", "b", false, "Always attach geolocation (PIDF-LO) to emergency calls."],
    ["AllowGeolocationForEmergencyCallsWhileInboundRoaming", "b", false, "Also attach geolocation when inbound roaming."],
    ["AlwaysAddGeolocationToInviteForNormalSetupEmergencyCall", "b", false, "Attach geolocation to INVITE of normal-setup (undetected) emergency calls."],
    ["AlwaysAddGeolocationToUpdateForNormalSetupEmergencyCall", "b", false, "Attach geolocation to UPDATE of normal-setup emergency calls."],
    ["AllowIncomingUssdSessions", "b", false],
    ["AlwaysUnsubscribeFromRegEvents", "b", true, "Unsubscribe from reg-event package on deregistration."],
    ["AuthResponseTimeoutMilliseconds", "i", 15000],
    ["CallEndReasons", "d", null, "Overrides of the SIP status and Reason header (ReasonHeaderProtocol/Cause/Text) sent when a call ends locally. Keyed by end-reason name."],
    ["CallSetupPingTimerMilliseconds", "i", 0, "Keep-alive ping interval during call setup."],
    ["ClearRegistrationCallIdOnDeinitialization", "b", false, "Reset registration Call-ID when the IMS stack deinitializes."],
    ["ContactUser", "x", "", "User part of Contact (interpolated: MDN, +MDN, IMSI, ${MDN})"],
    ["ContinueEmergencyCallOnMediaTimeout", "b", false, "Keep emergency call up despite RTP inactivity timeout."],
    ["EmergencyMediaTimeoutDeferalTimerSeconds", "i", 300, "How long to defer ending an emergency call on media timeout."],
    ["ConvertSessionProgressToRinging", "b", true, "Treat 183 Session Progress as ringing indication."],
    ["CountryOfOriginationFormat", "e", "NONE", "How country-of-origin is conveyed in requests: NONE, PIDF, PANI, BOTH."],
    ["CSFBOnAccessBarred", "b", false, "Fall back to CS when IMS access is barred."],
    ["CheckContactHeaderOnRegisterResponse", "b", false],
    ["LocationForShortCodeCalls", "e", "NONE", "Location attached to short-code calls: NONE, LATLONG, CIVIC, BOTH."],
    ["DefaultAuthAlgorithm", "s", "", "SIP digest algorithm when not negotiated (AKAv1-MD5, AKAv2-MD5)"],
    ["DefaultLocalSipPort", "i", 5060, "Local SIP port (0=ephemeral)"],
    ["DefaultRemoteSipPort", "i", 5060, "P-CSCF SIP port when not discovered."],
    ["DefaultRemoteSipPortOverwriteForEmergencyRoaming", "i", 0, "Remote SIP port override for emergency while roaming."],
    ["DeferMediaActivationOnSessionConfirmed", "b", false, "Start media only once session is confirmed (ACK)"],
    ["DeferIncomingMessagesUntilWake", "b", true],
    ["DeferReRegOnConnectivityDisable", "b", true],
    ["DeferReRegOnSubDisable", "b", true],
    ["EnableSignalingReduction", "b", false],
    ["DeregistrationWaitTimeoutMilliseconds", "i", 5000, "Wait for de-REGISTER response before tearing down."],
    ["DialogEventPackageSessionDescription", "b", false],
    ["DisableAccessNetworkInfoForAckAndCancel", "b", false, "Omit P-Access-Network-Info on ACK/CANCEL."],
    ["DisableRegistrationOnNotifyEvents", "a", "", "Array of reg-event NOTIFY events that disable IMS registration."],
    ["DontChangeProxiesDuringActiveCalls", "b", true],
    ["DontThrottleOnRegistrationErrorCodes", "s", "", "Registration error codes that must not trigger throttling."],
    ["DontSendPreconditionsIfCallWaitingDisabled", "b", false, "Omit preconditions when call waiting is off."],
    ["DropRegistrationOnCSFB", "b", true, "Deregister IMS when a CSFB occurs."],
    ["DropRegistrationOnSRVCC", "b", false, "Deregister IMS after SRVCC to CS."],
    ["DropRegistrationOnAirplaneModeToggle", "b", false, "Deregister on airplane-mode toggle."],
    ["DropRegistrationOnErrorCodes", "s", "", "Per-method error codes that drop registration (\"INVITE:408;REGISTER:503,...\")"],
    ["DropRegistrationOnWaitTimeout", "b", false, "Drop registration on wait timeout."],
    ["DropRegistrationOn305ToAllProxies", "b", false, "Drop registration once all proxies returned 305."],
    ["EarlyMediaNeedsHeader", "b", true],
    ["EchoRemotePreconditionStrength", "b", true],
    ["EmergencyAnonymousAutomaticRedial", "b", false, "Automatically redial emergency anonymously on failure."],
    ["EmergencyCallBackModeExpirationSeconds", "i", 0, "Emergency callback mode (ECBM) duration after an emergency call."],
    ["EmergencyCallSetupTimeoutSeconds", "i", 20, "Timeout for emergency call setup before fallback."],
    ["EmergencySessionSetupTimeoutSeconds", "i", 0, "Timeout for emergency session establishment."],
    ["EmergencyErrorResponsesToTriggerCSFB", "s", "", "SIP responses to emergency INVITE that trigger CS fallback."],
    ["EmergencyImpuRank", "s", "", "Order of IMPU selection for emergency (MDN@domain, IMSI@domain)"],
    ["EmergencyLocationLookupRequired", "b", true, "Require a location fix before placing emergency call."],
    ["EmergencyLocationLookupTimeoutSeconds", "i", 8, "Max wait for emergency location."],
    ["EmergencyLocationUpdateTimeSeconds", "i", 30, "Interval for emergency location updates during call."],
    ["EmergencyLocationUpdateTimeMinSeconds", "i", 5],
    ["EmergencyLocationUpdateTimeSMSFixed", "i", 5],
    ["SupportsCurrentLocationDiscovery", "b", false],
    ["EmergencyPreferredIdentity", "e", "IMSI", "Identity used for emergency when no valid USIM: IMSI or IMEI."],
    ["UseImsiAsContactForEmergencyCall", "b", false],
    ["EmergencyRegistrationRequestUri", "s", ""],
    ["EmergencyRegistrationTimeoutSeconds", "i", 10, "Timeout for emergency registration."],
    ["EmergencyRegistrationRetryResponses", "s", "", "Responses to emergency REGISTER that trigger a retry."],
    ["EmergencyRingbackTimerSeconds", "i", 600, "Ringback timer for emergency calls."],
    ["EmergencySMSModeExpirationSeconds", "i", 5],
    ["AddLocationToEmergencySMS", "b", false, "Attach location to emergency SMS (text-to-911)"],
    ["EmergencyURNs", "d", null, "Service URN (urn:service:sos.*) per dialled emergency number. Keyed by number; \"default\" covers unlisted numbers."],
    ["EnableATCommandMode", "b", false],
    ["EnableCellularNetworkInfo", "b", false, "Send P-Cellular-Network-Info (last cell) when on Wi-Fi."],
    ["PreferPCellularNetworkInfo", "b", true, "Prefer P-Cellular-Network-Info over PANI for Wi-Fi location."],
    ["EnableEmergencyRegistration", "b", true, "Allow emergency registration at all."],
    ["EnableForking", "b", true, "Support SIP forking of outgoing INVITE."],
    ["EnableLastAccessNetworkInfo", "b", false, "Send P-Last-Access-Network-Info."],
    ["EnableReasonHeaderInBye", "b", true],
    ["EnableRport", "b", true],
    ["EnableSenderName", "b", true, "Display the SIP sender name (From/PAI display-name) for incoming calls."],
    ["EnableSessionId", "b", true, "Add Session-ID header to calls."],
    ["EnableRegistrationSessionId", "b", true, "Add Session-ID header to REGISTER."],
    ["EndCallOnAudioBearerRevoked", "b", false, "End call when the voice bearer (QCI1) is revoked."],
    ["EnforceMaximumEmergencyExpirationSeconds", "i", 300, "Cap on emergency registration expiry."],
    ["EPSFallbackTimerSeconds", "i", 0, "Timer waiting for EPS fallback to complete."],
    ["FastEmergencyLocationEnabled", "b", false, "Use fast (early) location for emergency calls."],
    ["FastEmergencyLocationTimeoutSeconds", "i", 2],
    ["FatalSmsErrors", "s", "", "SMS-over-IP error codes treated as fatal (no retry)"],
    ["FatalTransportErrors", "s", "49,65", "Socket errno values treated as fatal transport errors."],
    ["FeatureTagsEnabled", "b", true],
    ["ForbiddenRegistrationErrorCodes", "s", "", "Registration responses treated as 403-forbidden (e.g. -4XX = all 4xx)"],
    ["ForceResetExistingTransports", "b", false],
    ["ForceTcp", "b", false, "Force SIP over TCP."],
    ["ForceTls", "b", false, "Force SIP over TLS."],
    ["ForcedFeatureTags", "s", "", "Feature tags always registered (e.g. voice,sms / ipcall)"],
    ["FuzzyContactMatching", "b", true],
    ["HonorSimAccessClassBeforeBarring", "b", false, "Apply SIM access class before barring checks."],
    ["IPSecSegmentOffset", "i", 0, "Offset subtracted from MTU/MSS for IPsec overhead."],
    ["IPSecBringupUseNetworkPath", "b", true, "Bind IPsec bring-up to the network path."],
    ["IPSecBringupTimeoutMilliseconds", "i", 5000],
    ["AlwaysUseDefaultTransport", "b", false],
    ["DropTrafficOnUnknownTransports", "b", true],
    ["IgnoreDuplicateSDP", "b", true],
    ["IgnoreErrorsInTerminatedForks", "b", false, "Ignore errors from already-terminated forks."],
    ["IgnoreNonCompliantSupportedHeaders", "b", true, "Ignore malformed Supported headers."],
    ["IgnoreSessionRefreshErrors", "b", false, "Don't drop call on session-refresh errors."],
    ["IgnoreFromHeaderForSenderName", "b", true, "Don't use From header for caller name."],
    ["IgnoreOverridesForWPSCalls", "b", false, "Ignore carrier overrides for WPS (priority) calls."],
    ["IgnoreWPSCallsOverNR", "b", true],
    ["IgnoreNetworkUnreachableErrors", "b", false, "Ignore ENETUNREACH transport errors."],
    ["IgnoreLimitedServiceInEmergencyMode", "b", false],
    ["IgnoreReregistrationErrorCodes", "s", "408", "Re-registration error codes to ignore."],
    ["IgnoreWifiHotspot", "b", true, "Don't use IMS over Wi-Fi when joined to a personal hotspot."],
    ["IgnoreRegNotificationContactExpires", "b", false, "Ignore Contact expires in reg-event NOTIFY."],
    ["ImpuRank", "s", "", "Order of IMPU selection for normal registration (first, IMSI@domain, tel:MDN,...)"],
    ["IncomingCallEndReasons", "d", null, "Maps SIP failures on incoming calls to end events. Keyed by reason name; each entry has StatusCode, TerminationEvent and flags such as DisableCSFB."],
    ["IncomingPhoneNumberPrefixMap", "d", null, "Rewrites the prefix of incoming caller numbers. Keyed by prefix (e.g. +81); value = replacement."],
    ["IncompleteRegistrationThrottlingIntervalSeconds", "i", 30, "Throttle interval after incomplete registration."],
    ["InitialRemotePreconditionStrength", "s", "", "Assumed initial remote precondition strength (mandatory/optional)"],
    ["InviteErrorResponsesToTriggerCSFB", "s", "3XX,403,500,503,504"],
    ["IR92PreconditionSupport", "b", false],
    ["KillCallOnHoldResumeError", "b", true, "End call when hold/resume re-INVITE fails."],
    ["KillForkOnUpdateErrors", "s", "", "UPDATE error codes that kill the fork."],
    ["KillRegistrationOnHandoverTimeout", "b", true, "Drop registration on handover timeout."],
    ["LegacyImpuRank", "s", ""],
    ["LimitedConnectivityHysteresisTimeoutSeconds", "i", 1800],
    ["LimitedConnectivityHysteresisFromRegistration", "b", false],
    ["LocalQoSTimeoutMOSeconds", "i", 0, "Wait for dedicated bearer (local QoS) on MO calls."],
    ["LocalQoSTimeoutMTSeconds", "i", 0, "Wait for dedicated bearer on MT calls."],
    ["MaintainTransportForDurationOfSession", "b", false],
    ["MaxAuthRetries", "i", 2, "Max 401 auth retries."],
    ["MaxFatalRegistrationErrors", "i", 2, "Max fatal registration errors before giving up."],
    ["MaxForbiddenErrors", "i", 2, "Max 403 responses before disabling IMS."],
    ["MaxReRegistrationAttempts", "i", 1, "Max re-registration attempts."],
    ["AddLocationInInviteResponses", "s", "", "Responses (e.g. 180,183) that carry geolocation."],
    ["AddServicesToUssdSessions", "b", true],
    ["MaxRegistrationAttemptsPerProxy", "i", 5, "Registration attempts per P-CSCF before next."],
    ["MaxTransportErrors", "i", 0, "Transport errors tolerated before failover."],
    ["MaxUdpMessageSize", "i", 0, "SIP size above which TCP is used instead of UDP (RFC3261 1300 rule)"],
    ["MinSessionExpiresSeconds", "i", 90, "Min-SE for session timers."],
    ["MethodInPIDF", "s", "DBH_HELO", "<method> element in PIDF-LO."],
    ["NetworkBasedCallWaiting", "b", false, "Call waiting is network-controlled (not terminal-based)"],
    ["EnableVideoCallWaiting", "b", false, "Allow call waiting for video calls."],
    ["NetworkTerminationRetryIntervalSeconds", "i", 60, "Retry interval after network-initiated termination."],
    ["NonPrivateEmergencyPrefixes", "s", "", "Dial prefixes that force non-private emergency identity."],
    ["NoFallbackVoiceService", "b", false, "No CS fallback voice (\"CDMA-less\")"],
    ["NonFatalReInviteResponses", "s", "488", "Re-INVITE responses that are non-fatal."],
    ["NumberOfSilentRedialAttempts", "i", 0, "Silent redial attempts."],
    ["OnlyUpdatePreconditionsIfConfPresent", "b", true, "Send precondition UPDATE only if confirmation requested."],
    ["OutgoingDomain", "s", "", "Domain used for outgoing request URIs."],
    ["UseOutgoingSipUri", "b", false, "Use sip: URI (with OutgoingDomain) instead of tel: for outgoing calls."],
    ["PdnBringupTimerSeconds", "i", 720, "Max wait for IMS PDN bring-up."],
    ["PerCallQoSIndications", "b", true, "Expect per-call QoS indications from baseband."],
    ["Allow3DPIDFInMessages", "b", false, "Allow 3D (altitude) shapes in PIDF-LO."],
    ["PIDFGeoPrivShape", "e", "Circle", "Shape in PIDF-LO geopriv: Circle or Ellipsoid."],
    ["PIDFConfidence", "i", 95, "Confidence % in PIDF-LO."],
    ["PrackErrorDelayMilliseconds", "i", 0, "Delay before handling PRACK error."],
    ["PreconditionAllowMTUpdate", "b", false],
    ["PreconditionUpdateDelayTimerMilliseconds", "i", 2000, "Delay before precondition UPDATE."],
    ["Preconditions", "e", "None"],
    ["PreferredAuthQopList", "s", ""],
    ["PreferredSenderIdentity", "s", "", "Which header gives sender identity (first/from/PAI)"],
    ["PreferredSenderName", "s", ""],
    ["PrivacyHeaderValue", "s", "id", "Privacy header value."],
    ["PrivateEmergencyPrefixes", "s", "", "Dial prefixes that force private emergency identity."],
    ["QueueUnreliableProvisionalResponses", "b", true],
    ["ReRegisterOnErrorCodes", "s", "INVITE:494", "Per-method error codes triggering re-registration."],
    ["ReRegisterOnInternalRequestTimeout", "b", false, "Re-register on internal transaction timeout."],
    ["ReRegisterOnCellularHandover", "b", false, "Re-register after cellular handover."],
    ["RequireRegistrationOnEPSFallback", "b", false, "Require re-registration on EPS fallback."],
    ["ReRegistrationHysteresisTimerMilliseconds", "i", 0, "Hysteresis before re-registering."],
    ["ReSubscribeOnReRegistration", "b", false, "Re-SUBSCRIBE reg-event on re-registration."],
    ["RefreshRegistrationDuringECBM", "b", true, "Refresh registration during emergency callback mode."],
    ["RegSubscriptionEnabled", "b", true, "Subscribe to reg-event package."],
    ["RegSubscriptionExpirationSeconds", "i", 600000, "Expiry of reg-event subscription."],
    ["RegisterOnServiceUpdate", "b", true, "Re-register on service (capability) change."],
    ["SkipReRegisterWhenNetworkTypeChangedOnNrBetweenTddAndFdd", "b", false, "Skip re-registration on NR TDD<->FDD change."],
    ["SkipReRegisterUponRatChangeWhenThereIsNoConnectivity", "b", false, "Skip re-registration on RAT change without connectivity."],
    ["SkipSocketCloseWhenNetworkTypeChangedOnNrBetweenTddAndFdd", "b", false],
    ["RegistrationExpirationSeconds", "i", 600000, "Requested REGISTER expiry."],
    ["RegisterSmsWhenAccessBarringZero", "b", false, "Register SMS feature tag even if barring factor is 0."],
    ["RegisterSmsOnEmergencyPdn", "b", false],
    ["AlwaysCheckRegistrationRefreshTimerAfterSystemClockChange", "b", false, "Re-evaluate refresh timer after clock change."],
    ["RegistrationPolicy", "s", "default"],
    ["RegistrationRefreshCushionPercent", "i", 5, "Refresh registration this % before expiry."],
    ["RegistrationCoalesceCushionPercent", "i", 50],
    ["RegistrationRetryBaseTimeSeconds", "i", 120, "Base backoff for registration retries (RFC5626)"],
    ["RegistrationRetryMaxTimeSeconds", "i", 7200, "Max backoff for registration retries."],
    ["RegistrationRetryIntervals", "s", "30,30,60+15,120,480,900", "Explicit retry schedule; \"a+b\" = a + random(b); default 30,30,60+15,120,480,900."],
    ["RequiresIMSIInContactHeaderOfAnonymousEmergencyInvite", "b", false, "Put IMSI in Contact of anonymous emergency INVITE."],
    ["RegistrationThrottlingCushionPercent", "i", 5, "Cushion % for throttling timers."],
    ["RemoveForkOnTransactionDoesNotExist", "b", false, "Remove fork on 481."],
    ["ReportSipErrorsDuringReRegistration", "b", false, "Report SIP errors during re-registration."],
    ["RequireExplicitPortsForEmergencyRoutes", "b", false, "Require explicit ports in emergency Route headers."],
    ["RequireQoSBeforeRinging", "b", false, "Don't alert until QoS bearer is up."],
    ["RequirePreconditionsWhenSdpPresent", "b", true],
    ["RequirePreconditionsWhenMandatory", "b", true],
    ["VerstatFeatureCapability", "e", "Disabled", "STIR/SHAKEN verstat display: Disabled, Dynamic, Enabled."],
    ["EnableBrandedCalling", "b", false, "Enable branded calling (caller logo/name, RCD) processing."],
    ["SpamHeaderFeatureCapability", "e", "Disabled", "Network spam-risk header use: Disabled, Dynamic, Enabled."],
    ["ResetCallIdOnAuthChallenge", "b", true, "New Call-ID after auth challenge."],
    ["ResetCallIdOnInitialRegistration", "b", false, "New Call-ID on initial registration."],
    ["ResetConnectionsWhenClosedByPeer", "b", true],
    ["ResetSocketWhenNetworkChange", "b", true, "Recreate SIP sockets on network change."],
    ["ResetDisabledModeOnEvents", "s", "SimInserted,AirplaneModeToggled", "Events that clear IMS 'disabled' mode (SimInserted,AirplaneModeToggled,AccessNetworkChanged)"],
    ["ResetThrottlingOnEvents", "s", "SimInserted,AirplaneModeToggled"],
    ["RetryAfterStatusCodes", "s", "", "Status codes whose Retry-After is honored."],
    ["IgnoreRetryAfterStatusCodes", "s", ""],
    ["RestartRingbackTimerOn180", "b", false, "Restart ringback timer on each 180."],
    ["RingbackTimerSeconds", "i", 45],
    ["RingingTimerSeconds", "i", 40, "Max alerting time for incoming call before timeout."],
    ["SecurityAgreementOptions", "s", "", "Explicit Security-Client header value."],
    ["SecurityAgreementAlgs", "a", "hmac-md5-96,hmac-sha-1-96", "IPsec integrity algs offered in Security-Client."],
    ["SecurityAgreementEalgs", "a", "aes-cbc,null", "IPsec encryption algs offered."],
    ["SendAcceptContactInInvite", "b", true],
    ["SendAcceptContactInSms", "b", true],
    ["SendEmergencyLocationUpdates", "b", false, "Send location updates during emergency calls."],
    ["SendInitialInviteAsInactive", "b", false, "Send initial INVITE with a=inactive."],
    ["SendResumeInviteAsSendRecv", "b", true, "Resume re-INVITE uses sendrecv."],
    ["SendLocalTimeZoneInformation", "b", false, "Include local time zone (in PANI/headers)"],
    ["AllowRTTControlInSipUpdate", "b", false, "Allow RTT add/remove via SIP UPDATE."],
    ["SendOfferWithInvite", "b", true],
    ["SendPreconditionsInConfirmedSessions", "b", false, "Keep preconditions in confirmed-session re-INVITEs."],
    ["SendPreferredIdentity", "b", true],
    ["SendPreferredServiceInInvite", "b", false, "Add P-Preferred-Service (e.g. mmtel) to INVITE."],
    ["SendReInviteInInactiveSessions", "b", false, "Allow re-INVITE on inactive sessions."],
    ["ServiceClass", "d", null, "DSCP class for SIP signalling per access type. Keyed by access (WiFi, Hotspot, ...); values like CS5, CS6."],
    ["SessionExpiresSeconds", "i", 0, "Session-Expires for session timer (0=off)"],
    ["SpamCallRiskLevels", "d", null, "Network spam-score range per risk level. Keyed by low / medium / high; values like \"81:100\"."],
    ["SpamCallCategoryMapping", "a", "", "Array mapping network spam categories to iOS categories."],
    ["AllowEmergencyRegistrationInLimitedAccessOnWiFi", "b", true],
    ["SetSessionTimerRefresherInInitialRequest", "b", false, "Set refresher= in initial INVITE."],
    ["SetCountryWithCampedPANI", "b", false, "Derive country from camped PANI."],
    ["SRVCCCleanupTimeoutSeconds", "i", 10, "Cleanup timeout after SRVCC."],
    ["StartLocalQosTimerOnSessionProgress", "b", false, "Start local-QoS timer on 183."],
    ["StrictCallFlowTimeoutInMilliseconds", "i", 0],
    ["StrictTS24930PreconditionHeaders", "b", false, "Strict TS 24.930 precondition headers."],
    ["SubscriptionRetryMaxSeconds", "i", 900],
    ["SubscriptionRetryMinSeconds", "i", 0],
    ["SubscriptionTerminatedMeansRegistrationTerminated", "b", false, "Treat reg-event subscription termination as deregistration."],
    ["SupportPEarlyMediaHeader", "b", true],
    ["SystemWakeWaitTimeoutMilliseconds", "i", 1000],
    ["TLSKeepAliveIntervalSeconds", "i", 300, "TLS keep-alive interval."],
    ["TLSIdlePingIntervalSeconds", "i", 1800],
    ["PCSCFDomainName", "s", ""],
    ["AttestationPrivateKey", "s", ""],
    ["PinnedCertificateDigests", "a", ""],
    ["TCPIdlePingIntervalSeconds", "i", 0],
    ["CRLFMinimumPingIntervalSeconds", "i", 120],
    ["CRLFPingIntervalDeltaSeconds", "i", 60],
    ["SuccessfulCRLFPingsUntilIntervalGrowth", "i", 2],
    ["UseCrlfIntervalFromRegistrationKeep", "b", false],
    ["TcpIdleTimeoutSeconds", "i", 5, "TCP idle timeout (0=never)"],
    ["TransferWaitForHoldTimeout", "i", 5000],
    ["TransferWaitForJoinTimeout", "i", 5000],
    ["TransferHangupTimeout", "i", 5000],
    ["TransferorShouldSendByeRequest", "b", false, "Transferor sends BYE after REFER."],
    ["ExplicitTransferEnabled", "b", true],
    ["HoldTransferTargetSession", "b", false],
    ["TransportInitTimeoutSeconds", "i", 30],
    ["TriggerCSFBOnLocalQoSTimeoutMO", "b", true, "CSFB when MO local QoS times out."],
    ["TriggerCSFBOnLocalQoSTimeoutMT", "b", true, "CSFB when MT local QoS times out."],
    ["TriggerCSFBOnSDPError", "b", false, "CSFB on SDP negotiation error."],
    ["TriggerCSFBOnWaitForRingingTimeout", "b", true, "CSFB when no 180 within WaitForRingingTimerMO."],
    ["TimeoutRegistrationAllProxyErrorCodes", "s", "", "Error codes that time out registration on all proxies."],
    ["UseAoRForSmsSenderIdentity", "b", false],
    ["UseCIDUrlInPIDF", "b", false, "Reference PIDF body by cid: URL in Geolocation header."],
    ["UseCIDUrlInGeoBodyContentId", "b", false],
    ["UseTupleInPIDF", "b", false, "Use <tuple> element in PIDF-LO."],
    ["UseCampedAccessNetworkInPANI", "b", false, "Use camped (not serving) cell in PANI."],
    ["UseCompactHeaders", "b", false],
    ["UseCorrectAckConstruction", "b", true],
    ["UseStrictBearerPreconditions", "b", true],
    ["RequireBearerPortMatchForPreconditions", "b", false],
    ["UseBase64ForMultipartSMS", "b", true, "Base64-encode multipart SMS bodies."],
    ["UseCustomSSOAuth", "b", false, "Use carrier custom SSO authentication."],
    ["UseDialogEventPackage", "b", false, "Subscribe to dialog event package (call pull)"],
    ["UseDummyImeiCheckDigit", "b", true, "Use dummy IMEI check digit in instance id."],
    ["UseEphemeralSipSourcePortForTcp", "b", false, "Use ephemeral source port for TCP SIP."],
    ["UseFakeSAsForDeregistration", "b", false, "Use placeholder IPsec SAs to send de-REGISTER."],
    ["UseIPSec", "b", false],
    ["EnforceIPSecSetupCompletionCheck", "b", true, "Verify IPsec SA setup completed before use."],
    ["UseEphemeralRangeForIPSec", "b", true, "Choose IPsec ports from ephemeral range."],
    ["MaxIPSecTransportRetries", "i", 10, "Max IPsec transport retries."],
    ["DefaultIPSecPort", "i", 42550, "Base protected client port for IPsec."],
    ["UseNextProxyForPcscfRestoration", "b", true],
    ["UseNormalIdentityForEmergencyCalls", "b", false, "Use normal IMPU for emergency calls."],
    ["UseNormalIdentityForEmergencyUSIM", "b", false, "Use normal identity for emergency with USIM."],
    ["UsePublicDomainForPhoneContext", "b", false, "Use public domain in phone-context."],
    ["UserAgentHeaderValue", "x", "${OS}/${OS_VERSION} ${DEVICE}", "User-Agent template (${OS}/${OS_VERSION} ${DEVICE})"],
    ["UssdResponseTimeoutMilliseconds", "i", 10000, "USSD-over-IMS response timeout."],
    ["ValidateSipMessageRecipient", "b", true, "Validate Request-URI matches own identity."],
    ["VirtualInterfaceMtu", "i", 2000, "MTU of IMS virtual interface."],
    ["WaitForAckBeforeEndingCallTimeoutMilliseconds", "i", 4000],
    ["WaitForByeResponseTimeoutMilliseconds", "i", 2000],
    ["WaitForCancelResponseTimeoutMilliseconds", "i", 4000],
    ["WaitForRingingTimerMOSeconds", "i", 20, "Outgoing call: wait for 180 before timeout/CSFB."],
    ["WaitForRingingTimerMTSeconds", "i", 25, "Incoming call: wait for local answer/ringing."],
    ["WaitForRingingTimerWPSSeconds", "i", 0, "Wait-for-ringing timer for WPS calls."],
    ["WPSCSFBDelayTimeout", "i", 2000],
    ["ResponseCodesBlockedForSilentRedialNRSANonEm", "s", "", "Codes that block silent redial for NR-SA non-emergency calls."],
  ],
  "Signaling/SipTimers": [
    ["A", "i", 0, "SIP Timer A ms (INVITE retransmit)"],
    ["B", "i", 0, "SIP Timer B ms (INVITE transaction timeout)"],
    ["C", "i", 0, "SIP Timer C ms (proxy INVITE)"],
    ["D", "i", 128000, "SIP Timer D ms (wait for response retransmits)"],
    ["E", "i", 0, "SIP Timer E ms (non-INVITE retransmit)"],
    ["F", "i", 0, "SIP Timer F ms (non-INVITE transaction timeout)"],
    ["G", "i", 0, "SIP Timer G ms (INVITE response retransmit)"],
    ["H", "i", 0, "SIP Timer H ms (wait for ACK)"],
    ["I", "i", 0, "SIP Timer I ms (wait for ACK retransmits)"],
    ["J", "i", 0, "SIP Timer J ms (non-INVITE response retransmits)"],
    ["T1", "i", 2000, "SIP T1 RTT estimate ms."],
    ["T2", "i", 16000, "SIP T2 max retransmit interval ms."],
    ["T4", "i", 17000, "SIP T4 max message lifetime ms."],
    ["200RetransmitTimer", "i", 0],
    ["AckReceiveTimeout", "i", 0, "Wait for ACK timeout ms."],
    ["AckRetransmitTimer", "i", 0, "200 OK retransmit-until-ACK timer."],
    ["RegAwaitAuthTimeout", "i", 0],
    ["InviteResponseTimeout", "i", 10000, "Wait for any response to INVITE ms."],
    ["EPSInviteResponseTimeout", "i", 0, "INVITE response timeout during EPS fallback."],
    ["EmergencyInviteResponseTimeout", "i", 0, "INVITE response timeout for emergency calls."],
  ],
  "ConferenceCalling": [
    ["AddServicesToContactInConferenceSubscribe", "b", false],
    ["AddSupportedHeaderToAllResponses", "b", true],
    ["AlwaysSubscribeToConferenceEvents", "b", false, "Subscribe to conference event package."],
    ["DisableMergeOnInviteErrorResponses", "s", "400,404,500"],
    ["conferenceServer", "x", "", "Conference factory URI (interpolated ${MCC}/${MNC})"],
    ["TreatAllNotificationsAsPartial", "b", false, "Treat conference NOTIFYs as partial state."],
    ["SendConferenceSubscribeInNewDialog", "b", false, "Send conference SUBSCRIBE in a new dialog."],
    ["SendConferenceSubscribeAfterRefers", "b", true, "SUBSCRIBE to conference only after REFERs."],
    ["SendReferToPeer", "b", false, "Merge by sending REFER to peer (vs. to conference)"],
    ["SerializeRefers", "b", true],
    ["SerializeParticipants", "b", false, "Add conference participants one at a time."],
    ["UseDomainForConferenceServer", "b", true],
  ],
  "Media": [
    ["AddBWSpecsAtSessionLevel", "b", false, "Put b= lines at session level."],
    ["AllowHoldMusic", "b", true, "Allow remote hold music (don't mute on hold)"],
    ["AllowIPv6UnicastAddress", "b", false, "Allow IPv6 unicast media addresses."],
    ["IgnoreLocalhostRemoteRtpAddress", "b", false],
    ["AlwaysPrintSDPFormatInfo", "b", false, "Always emit fmtp lines."],
    ["BandwidthSpecifierRRValue", "i", 100, "b=RR value."],
    ["BandwidthSpecifierRSValue", "i", 300, "b=RS value."],
    ["SuppressBSUntilPreconditionsMet", "b", false, "Omit b= until preconditions met."],
    ["DTMFDigitDurationMilliseconds", "i", 100, "RFC4733 DTMF digit duration."],
    ["DTMFInterDigitIntervalMilliseconds", "i", 100, "Gap between DTMF digits."],
    ["DTMFVolume", "i", 0, "DTMF event volume."],
    ["EnableBandwidthSpecifiers", "b", false, "Add b=AS/RS/RR bandwidth lines to SDP."],
    ["EnableRemoteRTCPDeactivation", "b", false, "Honor remote RTCP deactivation (b=RS:0/RR:0)"],
    ["EnableDTX", "b", true],
    ["EnableRingbackAudioForTextCalls", "b", false, "Play ringback for RTT calls."],
    ["EnableRTCPExtendedReports", "b", false, "Send RTCP XR."],
    ["EnableSDPCandidateAttribute", "b", false, "Add a=candidate."],
    ["HideSessionLevelDirection", "b", false, "Omit session-level direction attribute."],
    ["HoldHeartbeatIntervalSeconds", "i", 2, "RTP/RTCP keepalive interval while on hold."],
    ["InactivityTimerRTCPSeconds", "i", 10, "RTCP inactivity timeout."],
    ["InactivityTimerRTPSeconds", "i", 10, "RTP inactivity timeout ending call."],
    ["IncludeEVSIOModes", "b", false, "Advertise EVS AMR-WB IO mode."],
    ["IncludeSDPMaxRed", "b", false, "Include a=maxred."],
    ["IncludeSDPModeChangeCapability", "b", true, "Include mode-change-capability fmtp."],
    ["IncludeSDPModeChangeNeighbor", "b", false],
    ["IncludeSDPModeChangePeriod", "b", false, "Include mode-change-period."],
    ["LocalRTCPReportIntervalSeconds", "i", 5],
    ["MaxPacketizationTime", "i", 240, "a=maxptime."],
    ["MaxRedundancy", "i", 0, "Max redundancy ms."],
    ["ModeChangeCapability", "i", 2, "AMR mode-change-capability value."],
    ["ModeChangeNeighbor", "i", 0],
    ["ModeChangePeriod", "i", 2],
    ["ModeSetAMRNB", "s", "", "AMR-NB mode-set."],
    ["ModeSetAMRWB", "s", "", "AMR-WB mode-set."],
    ["SDPTemplate", "s", ""],
    ["BindMediaToTransportInterface", "b", true],
    ["EnforceEarlyMediaDirection", "b", false, "Honor early-media direction."],
    ["EnforceEarlyMediaInactiveDirection", "b", false],
    ["UseRemoteMediaOrder", "b", true, "Answer using remote codec order."],
    ["UseRTPDetectionAutoStart", "b", false, "Auto-start RTP detection."],
    ["LinkMonitorPreference", "e", ""],
    ["EnableIncomingDTMF", "b", false, "Detect incoming RFC4733 DTMF."],
    ["OriginUsername", "x", "", "SDP o= username (interpolated)"],
    ["PacketAlignmentAMRNB", "s", "all", "AMR-NB packing: all, octetAlignedOnly, bandwidthEfficientOnly."],
    ["PacketAlignmentAMRWB", "s", "all", "AMR-WB packing: all, octetAlignedOnly, bandwidthEfficientOnly."],
    ["PacketizationTime", "i", 20],
    ["PayloadTypeBWEfficientAMRNB", "i", 102, "RTP PT for AMR-NB BE."],
    ["PayloadTypeBWEfficientAMRWB", "i", 104, "RTP PT for AMR-WB BE."],
    ["PayloadTypeDTMF16K", "i", 105, "RTP PT telephone-event/16000."],
    ["PayloadTypeDTMF8K", "i", 100, "RTP PT telephone-event/8000."],
    ["PayloadTypeOctetAlignAMRNB", "i", 108, "RTP PT AMR-NB octet-aligned."],
    ["PayloadTypeOctetAlignAMRWB", "i", 110, "RTP PT AMR-WB octet-aligned."],
    ["PayloadTypeTTY", "i", 111],
    ["PayloadTypeTTYRedundancy", "i", 112],
    ["PreferredAMRNBMode", "i", 7],
    ["PreferredAMRWBMode", "i", 2],
    ["RTCPXRBasebandSupport", "d", null, "Dict of RTCP-XR report blocks supported in baseband (stat-summary, voip-metrics)"],
    ["RTTBandwidthSpecifierASValue", "i", 4, "b=AS for RTT text stream."],
    ["RTTBandwidthSpecifierRTCPPercentage", "i", 10, "RTCP share % for RTT stream."],
    ["RTTUpgradeResponseTimeoutMilliseconds", "i", 10000],
    ["StopLocalRingbackToneOn181", "b", true, "Stop local ringback on 181 (forwarded)"],
    ["RTCPIntervalSeconds", "i", 0, "RTCP report interval."],
    ["RTTNegotiationTimerSeconds", "i", 3],
    ["SRTPCryptoSuite", "s", "", "SRTP crypto suite (AES_CM_128_HMAC_SHA1_80)"],
    ["SRTPEndToAccessEdgeProtection", "b", false, "Use SRTP e2ae (end-to-access-edge) security."],
    ["SRTPUnauthenticatedSRTP", "b", false, "SRTP without authentication."],
    ["SRTPUnencryptedSRTCP", "b", false, "Unencrypted SRTCP."],
    ["SRTPUnencryptedSRTP", "b", false, "Unencrypted SRTP."],
    ["SampleRateTTY", "i", 1000],
    ["AudioCodecs", "d", null, "Codec definitions. Keyed by dynamic RTP payload type; each entry has EncodingName, SampleRate and fmtp parameters."],
    ["AudioCodecList", "s", ""],
    ["EVSHardBwLimit", "s", "nb-wb", "EVS bandwidth cap (nb-wb default; nb-swb)"],
    ["EVSHardBrLimit", "s", "5.9-24.4", "EVS bitrate range cap."],
    ["RestrictSessionEVSBandwidth", "b", true, "Restrict EVS bandwidth at session level."],
    ["OrderEVSCodecsByCodecID", "b", true, "Order EVS codecs by codec id."],
    ["SupportAMRNB", "b", true, "Offer AMR-NB."],
    ["SupportAMRWB", "b", true, "Offer AMR-WB."],
    ["SupportPCMA", "b", false, "Offer G.711 A-law."],
    ["SupportPCMU", "b", false, "Offer G.711 mu-law."],
    ["UseEphemeralRTPPorts", "b", false, "Pick ephemeral RTP ports."],
    ["UseRestrictiveDirectionWhenCreatingAnswer", "b", true, "Answer with most restrictive direction."],
    ["UseSDPTemplateForAllInvites", "b", false, "Use static SDP template for every INVITE."],
    ["UseSDPTemplateForUpdates", "b", false, "Use SDP template for UPDATEs."],
    ["SuppressOctetAlignAttributeForBECodecs", "b", true, "Omit octet-align=0 for BE codecs."],
    ["SelectForkWithActiveEarlyMedia", "b", false, "Pick fork that has early media."],
    ["SelectLatestForkWithActiveEarlyMedia", "b", false, "Pick latest fork with early media."],
    ["RewriteNonCompliantPtimeAttribute", "b", false],
  ],
  "Media/VoiceOnAP": [
    ["EnableAPOnlyMode", "b", true, "Run voice media on AP (not baseband)"],
    ["EnableANBR", "b", false],
    ["EnableRateAdaptation", "b", false],
  ],
  "XCAP": [
    ["Auid", "s", "simservs.ngn.etsi.org", "XCAP AUID path."],
    ["BsfHost", "s", "", "GBA BSF host."],
    ["BsfPort", "i", 0, "GBA BSF port."],
    ["BsfUseSecureTransport", "b", false, "HTTPS to BSF."],
    ["ContentType", "s", "application/xcap-el+xml", "XCAP PUT content type."],
    ["DisableOnNetworkError", "b", true, "Disable XCAP (fall back to CS SS) on network error."],
    ["FetchAllCDIVRules", "b", false, "Fetch all call-diversion rules at once."],
    ["ForbiddenHttpErrorCodes", "s", "400,403,404,500,501,502,503,504", "HTTP codes treating XCAP as forbidden."],
    ["ImeiHeaderNameInBsfRequest", "s", "", "Header name carrying IMEI to BSF (X-TMUS-IMEI)"],
    ["ImpuRank", "s", "", "Order of IMPU selection for normal registration (first, IMSI@domain, tel:MDN,...)"],
    ["NafHost", "s", "", "XCAP NAF/AS host."],
    ["NafPort", "i", 0, "XCAP NAF port."],
    ["NafUseSecureTransport", "b", false, "HTTPS to NAF."],
    ["PreferredGbaMode", "s", "GBA_ME", "GBA mode (GBA_ME default)"],
    ["RequestTimeoutValue", "i", 30],
    ["UnsolicitedRequestDelay", "i", 10, "Delay before unsolicited XCAP request."],
    ["ReuseAuthCredentials", "b", true, "Reuse GBA credentials across requests."],
    ["ServeMultipleCDIVRulesPerRequest", "b", false, "Put several CDIV rules in one request."],
    ["SupportsCFErasure", "b", true, "Supports call-forward erasure."],
    ["SupportCFMediaTag", "b", false, "Include media tag in CF rules."],
    ["SupportsCB", "b", false, "Supports call barring over XCAP."],
    ["SupportCBMediaTag", "b", false, "Include media tag in CB rules."],
    ["UtInterfaceType", "s", ""],
    ["useSecureTransport", "b", false, "XCAP over HTTPS."],
    ["XcapHttpVersion", "s", "1.1", "HTTP version for XCAP."],
  ],
  "Internal": [
    ["AllowRTPStackHandover", "b", true],
    ["MediaSessionHandoverTimeoutMilliseconds", "i", 10000],
    ["AutoRingTimerMilliseconds", "i", 50],
    ["ClearThrottlingOnSocketErrors", "s", "49,60,65", "Socket errors that clear throttling."],
    ["ConferenceParticipantJoinTimeoutMilliseconds", "i", 5000],
    ["ConferenceWaitForHoldTimeoutMilliseconds", "i", 15000, "Wait for hold before conference merge."],
    ["CSFBDeregisterTimeoutSeconds", "i", 6],
    ["EndConferenceOn405", "b", true],
    ["DeviceIMEI", "s", ""],
    ["DisableDeviceSVN", "b", true],
    ["DisplayName", "s", ""],
    ["DigestPassword", "s", ""],
    ["DigestUsername", "s", ""],
    ["Domain", "s", ""],
    ["DropIncoming", "s", ""],
    ["DropOutgoing", "s", ""],
    ["FatalRegistrationErrorCodes", "s", ""],
    ["EnableBasebandAssertOnInitializationFailure", "b", false],
    ["HoldResumeTimerMilliseconds", "i", 10000],
    ["HonorForbiddenRetryAfter", "b", true],
    ["IgnoreSessionTimerExpiration", "b", false],
    ["InternalDisableSipInstance", "b", false],
    ["Impi", "s", ""],
    ["Impu", "s", ""],
    ["LoggingParams", "s", ""],
    ["MaxCallCount", "i", 3],
    ["MaxProxyResolveAttempts", "i", 5],
    ["MediaAddressType", "s", ""],
    ["MediaInterface", "s", ""],
    ["MediaInitTimeoutMilliseconds", "i", 5000],
    ["MultiCallHoldResumeTimerMilliseconds", "i", 5000],
    ["NewSubscriptionOnReRegistration", "b", false],
    ["NetworkInterface", "s", ""],
    ["OutgoingUri", "s", ""],
    ["PcscfOverride", "s", ""],
    ["RejectSMSWithFakeTimeout", "b", false],
    ["ReRegisterOnMobikeHandover", "b", false, "Re-register after MOBIKE (ePDG) handover."],
    ["ResponseCodesAllowedForSilentRedial", "s", "*"],
    ["RegistrationExpirationCushionSeconds", "i", 600],
    ["RegistrationRefreshCushionCapSeconds", "i", 900],
    ["RegistrationThrottlingCushionCapSeconds", "i", 30],
    ["SessionExpiresCushion", "i", 5],
    ["ShutdownWaitTimeSeconds", "i", 1],
    ["TTYReinviteTimeoutMilliseconds", "i", 2000],
    ["UseAPMediaStack", "b", false],
  ],
  "Cert": [
    ["ResetCallIdOn401WithoutSecurityServer", "b", false, "New Call-ID on 401 without Security-Server."],
    ["UseUacAsRefresher", "b", false, "UAC is session refresher."],
    ["AddPreconditionToSupportedHeaderIfEnabled", "b", false, "Add precondition to Supported."],
    ["UseInviteToRefreshSessionIfRemoteDoesNotAllowUpdate", "b", false, "Refresh with re-INVITE if UPDATE not allowed."],
    ["DoNotRefreshSessionIfNoSessionExpiresHeaderFromRemote", "b", false, "Skip refresh without Session-Expires."],
    ["SendPreconditionsInPrack", "b", false, "Preconditions in PRACK."],
  ],
  "IPTelephony": [
    ["pcscf", "s", "", "Static P-CSCF override."],
  ],
  "Voice": [
    ["BlockSilentRedialOverCS", "b", false, "Block silent redial over CS."],
  ],
  "CallTransfer": [
    ["CallTransferDialNumber", "s", "", "Number dialed for call transfer/pull."],
    ["CallTransferRequestUri", "s", "", "Request-URI for call pull (e.g. pull-VoLTE-active@...)"],
    ["CallTransferToUri", "s", "", "Refer-To URI for call pull."],
  ],
  "Lazuli": [
    ["SwitchoverSize", "i", 0],
    ["MessageMaxSize", "i", 8192],
    ["LazuliConferenceFactory", "s", ""],
    ["CarrierBased", "b", false],
    ["RCSVendorID", "i", 0],
    ["InfoRequestTimeoutSeconds", "i", 20],
  ],
};

/** Registry section names, in registration order. */
export const IMS_SECTIONS: readonly string[] = Object.keys(SECTIONS);

let index: Map<string, ImsSetting[]> | undefined;

function build(): Map<string, ImsSetting[]> {
  const m = new Map<string, ImsSetting[]>();
  for (const [section, rows] of Object.entries(SECTIONS)) {
    for (const [key, type, dflt, note] of rows) {
      const s: ImsSetting = { key, section, type };
      if (dflt !== undefined && dflt !== null) s.default = dflt;
      if (note) s.note = note;
      const values = IMS_ENUMS[key];
      if (values) s.values = values;
      const list = m.get(key);
      if (list) list.push(s);
      else m.set(key, [s]);
    }
  }
  return m;
}

/** Every registered setting (one entry per key and section). */
export function imsSettings(): ImsSetting[] {
  index ??= build();
  return [...index.values()].flat();
}

/** Look up an IMSConfig key, following legacy renames. `section` picks between
 *  registrations of the same key ("ImpuRank" is in Signaling and XCAP); it may be a
 *  full section ("Signaling/SipTimers") or its last part ("SipTimers"). */
export function describeImsSetting(key: string, section?: string): ImsSetting | undefined {
  index ??= build();
  const renamed = IMS_RENAMES[key];
  const list = index.get(renamed ?? key);
  if (!list) return undefined;
  const hit = (section && list.find((s) => s.section === section || s.section.endsWith(`/${section}`))) || list[0];
  return renamed ? { ...hit, renamedFrom: key } : hit;
}

/* ------------------------------------------------------------------------ */
/* Call end reasons                                                         */
/* ------------------------------------------------------------------------ */

/** ims::DisconnectReason::ReasonCode, by value. These names are the valid
 *  `TerminationEvent` strings in IncomingCallEndReasons entries.
 *  libIPTelephony.dylib: ImsCallSessionTerminationBaseEvent::nameForReason */
export const TERMINATION_EVENTS: readonly string[] = [
  "LocalHangup", "RemoteHangup", "LocalCallRejected", "RemoteCallRejected", "LocalRequestCanceled",
  "RemoteRequestCanceled", "CallAnsweredElsewhere", "SecondaryDeviceInUse", "SilentHangup", "TransferredToOtherDevice",
  "UnknownError", "NetworkError", "RemoteRequestTerminated", "RequestTimeout", "TemporarilyUnavailable",
  "EmergencySessionRequired", "Forbidden", "InviteResponseTimeout", "LocalError", "MediaError",
  "MediaTimeout", "MediaHeartbeatTimeout", "LocalSocketError", "WaitForRingingTimeout", "LocalQosTimeout",
  "VoiceNotSupported", "EmergencyStateExited", "AccessBarring", "OnEmergencyCall", "SdpError",
  "Deinitializing", "NoEmergencyCallLocation", "AudioUnit", "AVConferenceCrash", "LocalBusy",
  "BasebandCrash", "NetworkUnreachable", "RequiresRedial", "CallAudioServiceCrash",
];

/** A built-in end reason: SIP status (sent, or matched for incoming), ReasonCode, Reason text. */
export type EndReason = readonly [name: string, status: number, reason: number, text?: string];

/** Defaults for `IMSConfig.Signaling.IncomingCallEndReasons` (SIP failure received -> end event).
 *  libIPTelephony.dylib: ImsCallIncomingTerminationReasons::createDefaultReasonMap */
export const DEFAULT_INCOMING_END_REASONS: readonly EndReason[] = [
  ["Forbidden", 403, 16],
  ["NoEmergencyCallLocation", 503, 31, "Emergency calls over WiFi not allowed in this location"],
  ["TransferredToOtherDevice", 200, 9, "Call has been transferred to another device"],
  ["CallCompletedElsewhere", 200, 6, "Call completed elsewhere"],
  ["OtherSecondaryDeviceOnCall", 603, 7, "Secondary device already in use"],
  ["BusyHere", 486, 3],
  ["TransactionDoesNotExist", 481, 11],
  ["RequestTimeout", 408, 13],
  ["TemporarilyUnavailable", 480, 14],
  ["Decline", 603, 1],
  ["RequestTerminated", 487, 1],
  ["MediaTimeout", 0, 20, "RTP Timeout"],
  ["MediaHeartbeatTimeout", 0, 21, "RTCP Timeout"],
  ["SessionRedirected", 302, 11],
];

/** Defaults for `IMSConfig.Signaling.CallEndReasons` (local end -> SIP status and Reason header sent).
 *  libIPTelephony.dylib: ImsCallTerminationReasons::createDefaultReasonMap */
export const DEFAULT_END_REASONS: readonly EndReason[] = [
  ["UserTriggered", 486, 0, "User Triggered"],
  ["RejectedByUser", 486, 0, "Call Rejected By User"],
  ["CallWaitingDisabled", 486, 0, "Call Waiting Disabled"],
  ["DoNotDisturb", 486, 0, "Call Rejected By User"],
  ["Blocked", 486, 0, "Call Rejected By User"],
  ["SRVCC", 500, 8, "SRVCC"],
  ["DeferToSecondary", 480, 0, "Deferred to Secondary Device"],
  ["AvoidVoicemail", 607, 0, "Do not send to voicemail"],
  ["CallCompletedElsewhere", 487, 6, "Call completed elsewhere"],
  ["OtherSecondaryDeviceOnCall", 603, 7, "Secondary device already in use"],
  ["EstablishingAnotherCall", 486, 34, "Establishing Another Call"],
  ["AlreadyOnMaxCalls", 486, 34, "Already On Max Calls"],
  ["NoLTE", 488, 25, "Moved to non-LTE access network"],
  ["NonVoiceLTE", 488, 25, "Moved to LTE without VoLTE support"],
  ["NotVoiceRegisteredNoLTE", 488, 25, "Not Acceptable Here"],
  ["NotVoiceRegisteredNonVoiceLTE", 488, 25, "Not Acceptable Here"],
  ["SessionExpired", 500, 11, "Session Expired"],
  ["MediaError", 500, 19],
  ["MediaTimeout", 500, 20, "RTP Timeout"],
  ["MediaHeartbeatTimeout", 500, 21, "RTCP Timeout"],
  ["NoAnswer", 486, 2, "No Answer"],
  ["JoinedConference", 500, 0, "Joined N-way Call"],
  ["ConferenceJoinFailed", 500, 11, "Conference join failed"],
  ["EmptyConference", 500, 0, "Conference call is empty"],
  ["ReferFailed", 500, 11, "REFER failed"],
  ["OnEmergencyCall", 486, 28, "On Emergency Call"],
  ["InvalidSdp", 488, 29, "Invalid SDP"],
  ["MissingSdp", 488, 29, "Missing SDP Answer"],
  ["CodecNotSupported", 488, 11, "Not Acceptable Here"],
  ["ReceivedRejectSdp", 488, 11, "Received reject SDP"],
  ["NoAckReceived", 500, 11, "No ACK received"],
  ["PreconditionFailure", 580, 23, "Precondition Failure"],
  ["WaitForRingingTimeout", 500, 23, "Remote device didn't ring"],
  ["LocalQualityOfServiceTimeout", 580, 24, "Local QoS not established"],
  ["HoldResumeTimeout", 500, 11, "Hold/resume timeout"],
  ["Deregistering", 486, 0, "Deregistering"],
  ["Deinitializing", 486, 30, "Deregistering"],
  ["RemoteCancel", 487, 5, "Remote end CANCELed a completed transaction"],
  ["ExitEmergencyState", 500, 26, "Emergency state exited"],
  ["AudioUnit", 500, 32],
  ["AVConferenceCrash", 500, 33],
  ["CallAudioServiceCrash", 500, 38],
  ["BasebandCrash", 500, 35],
  ["BearerRevoked", 500, 11, "Media bearer loss"],
  ["TransferredToOtherDevice", 200, 0, "Transferred to another device"],
  ["InternalError", 500, 18],
  ["NetworkError", 500, 11],
  ["EmergencyUserTriggered", 486, 0, "User Triggered"],
  ["EmergencyUserTriggeredTimeout", 486, 0, "User ends call SIP response time-out"],
  ["EmergencyTimeout", 500, 17, "SIP response time-out"],
  ["EmergencySetupTimeout", 500, 23, "Call-setup time-out"],
  ["TerminateChat", 200, 0],
];

/** The built-in default for a CallEndReasons / IncomingCallEndReasons entry name
 *  (a name listed twice in a map resolves to its first row). */
export function defaultEndReason(name: string, incoming: boolean): EndReason | undefined {
  return (incoming ? DEFAULT_INCOMING_END_REASONS : DEFAULT_END_REASONS).find((r) => r[0] === name);
}
