/**
 * Carrier logos, by the words of a bundle's name (split on "_"). Each logo is
 * static/carriers/<slug>.webp: a carrier icon, on a 96px
 * white tile. A rule word with "_" in it is a run of words, for a carrier the
 * plain brand word would mistake for another (Cellcom_il is not CellcomWI).
 *
 * The longest run that matches wins, then the one further right, so an MVNO
 * named after its host network gets its own logo: ATT_RedPocket_US is Red Pocket.
 */

const LOGOS = {
  "1global": ["Truphone"],
  "1und1": ["1and1"],
  "2degrees": ["2degrees"],
  "a1": ["mobilkom"],
  "airalo": ["AirGSM"],
  "airtel": ["BhartiAirtel"],
  "ais": ["AIS"],
  "alaska-communications": ["ACS"],
  "alcom": ["Alcom"],
  "alfa": ["Alfa"],
  "algar": ["Algar"],
  "aliv": ["Aliv"],
  "almadar": ["Almadar"],
  "alosim": ["AffinityClick"],
  "altel": ["Altel"],
  "andorra-telecom": ["Mobiland"],
  "antel": ["Antel"],
  "appalachian-wireless": ["Appalachian"],
  "apua": ["APUA"],
  "astca": ["ASTCA"],
  "atn": ["ATN"],
  "atom": ["Telenor_mm"],
  "att": ["ATT", "iusacell"],
  "au": ["KDDI"],
  "awcc": ["AWCC"],
  "azercell": ["Telia_az"],
  "bakcell": ["Bakcell"],
  "banglalink": ["Banglalink"],
  "base": ["BASE"],
  "batelco": ["Batelco"],
  "beeline": ["VimpelCom"],
  "bell": ["Bell"],
  "bhutan-telecom": ["BhutanTelecom"],
  "bics": ["BICS"],
  "biglobe": ["BIGLOBE"],
  "bite": ["Bite"],
  "bluesky": ["Bluesky"],
  "bmobile": ["CW_tt"],
  "boost-mobile": ["Boost", "Dish"],
  "bouygues-telecom": ["Bouygues"],
  "bravado-wireless": ["Bravado", "CrossWireless"],
  "bsnl": ["BSNL"],
  "bt": ["BT"],
  "btc": ["BTC"],
  "btc-bahamas": ["CW_bs"],
  "c-spire": ["CellularSouth"],
  "cable-wireless-seychelles": ["CW_sc"],
  "cablenet": ["Cablenet"],
  "carolina-west": ["CWW", "CarolinaWest"],
  "cbn": ["CBN"],
  "celcomdigi": ["Celcom", "DiGi"],
  "cell-c": ["CellC"],
  "cellcard": ["Cellcard"],
  "cellcom-israel": ["Cellcom_il"],
  "cellcom-us": ["Cellcom", "CellcomWI"],
  "cellfie": ["VimpelCom_ge"],
  "chatr": ["chatr"],
  "china-mobile": ["CMCC"],
  "china-telecom": ["ChinaTelecom"],
  "china-unicom": ["Unicom"],
  "chunghwa-telecom": ["Chunghwa"],
  "claro": ["Claro", "Comcel", "Porta"],
  "cnt": ["CNT"],
  "comviq": ["Comviq"],
  "consumer-cellular": ["CC"],
  "copper-valley-telecom": ["CopperValley", "CopperValleyTelecom"],
  "coriolis": ["Coriolis"],
  "cox-mobile": ["Cox"],
  "credo-mobile": ["Credo"],
  "cricket": ["Cricket", "aio"],
  "csl": ["CSL", "PCCW"],
  "ctm": ["CTM"],
  "cyta": ["Cyta"],
  "dhiraagu": ["Dhiraagu"],
  "dialog": ["Dialog"],
  "digi-belize": ["BTL"],
  "digicel": ["Digicel"],
  "digitel": ["Digitel"],
  "djezzy": ["Djezzy"],
  "dna": ["DNA", "DNAPro"],
  "docomo": ["Docomo"],
  "dstcom": ["DSTCom"],
  "dtac": ["dtac"],
  "du": ["du"],
  "eastlink": ["Eastlink"],
  "econet": ["Econet"],
  "ee": ["EE", "TMobile_uk"],
  "eir": ["Meteor"],
  "elisa": ["Elisa", "Saunalahti", "elisa"],
  "enetworks": ["ENetworks"],
  "entel": ["Entel", "EntelPCS"],
  "epic": ["Vodafone_mt"],
  "esimgo": ["eSIMGO"],
  "etb": ["ETB"],
  "etisalat": ["Etisalat"],
  "fareastone": ["APT", "FarEasTone"],
  "faroese-telecom": ["FaroeseTelecom"],
  "fastweb": ["Fastweb"],
  "fido": ["Fido"],
  "firstnet": ["FirstNet"],
  "fizz": ["Fizz"],
  "fl1": ["TelecomLiechtenstein"],
  "flexiroam": ["Flexiroam"],
  "flow": ["CW", "Chippie"],
  "free": ["Free"],
  "freedom-mobile": ["FreedomMobile"],
  "freenet": ["Debitel"],
  "fsmtc": ["FSMTC"],
  "gci": ["AlaskaWireless", "GCI"],
  "giffgaff": ["Giffgaff"],
  "giga": ["giga"],
  "gigsky": ["GigSky"],
  "glo": ["Globacom"],
  "go-malta": ["GoMobile"],
  "golan-telecom": ["Golan"],
  "grameenphone": ["Grameenphone"],
  "gta": ["GTA"],
  "helia": ["OPT"],
  "hkbn": ["HKBN"],
  "ho-mobile": ["Ho"],
  "holafly": ["Holafly"],
  "ice-norway": ["Ice"],
  "id-mobile": ["iD"],
  "iliad": ["Iliad"],
  "imagine": ["Imagine"],
  "indosat": ["Indosat"],
  "inland-cellular": ["Inland"],
  "inwi": ["INWI"],
  "ipko": ["TelekomSlovenije_xk"],
  "ite": ["Choice", "ITE"],
  "izi": ["Izi"],
  "jawwal": ["Jawwal"],
  "jazz": ["Mobilink", "Warid"],
  "jazztel": ["Jazztel"],
  "jcom": ["JCOM"],
  "jio": ["RelianceJio"],
  "jt": ["JerseyTelecom"],
  "kcell": ["Telia_kz"],
  "kena-mobile": ["Kena"],
  "kktcell": ["KKTCELL"],
  "knowroaming": ["KnowRoaming"],
  "kolbi": ["ICE"],
  "koodo": ["Koodo"],
  "kore": ["KORE"],
  "korek": ["Korek"],
  "kpn": ["KPN"],
  "kt": ["KTF"],
  "kyivstar": ["Kyivstar"],
  "la-poste-mobile": ["LPM"],
  "lao-telecom": ["Laotel"],
  "lebara": ["Lebara"],
  "lg-uplus": ["LGU"],
  "liberty": ["Liberty"],
  "life-belarus": ["life"],
  "lifecell": ["lifecell"],
  "lmt": ["LMT"],
  "lotusflare": ["LotusFlare"],
  "lowi": ["Lowi"],
  "lucky-mobile": ["Lucky"],
  "lum": ["Lum"],
  "m1": ["MobileOne"],
  "magti": ["Magticom"],
  "manx-telecom": ["ManxTelecom"],
  "maroc-telecom": ["Maroc"],
  "mas-movil": ["CW_pa"],
  "mascom": ["Mascom"],
  "masmovil": ["Masmovil"],
  "maxis": ["Maxis"],
  "megafon": ["MegaFon"],
  "melita": ["Melita"],
  "meo": ["TMN"],
  "metfone": ["Metfone"],
  "metro-by-t-mobile": ["MetroPCS"],
  "mint-mobile": ["UltraMint"],
  "mobicom": ["MobiCom"],
  "mobifone": ["Mobifone"],
  "mobilis": ["Mobilis"],
  "mobily": ["mobily"],
  "mobitel": ["Mobitel"],
  "moldcell": ["Telia_md"],
  "monaco-telecom": ["MonacoTel", "MonacoTelecom"],
  "moov-africa": ["Moov"],
  "movistar": ["Telefonica", "movistar"],
  "mta": ["MTA"],
  "mtc": ["MTC"],
  "mtel": ["TelekomSrbija_ba", "TelekomSrbija_me"],
  "mtn": ["MTN"],
  "mts": ["MTS"],
  "mts-serbia": ["TelekomSrbija"],
  "mtx": ["MTX"],
  "nar": ["Azerfon"],
  "natcom": ["Natcom"],
  "ncell": ["Ncell"],
  "nemont": ["Nemont", "NemontWireless"],
  "nepal-telecom": ["NepalTelecom"],
  "nex-tech": ["NexTech"],
  "norlys": ["Telia_dk"],
  "nos": ["Optimus"],
  "nova": ["Nova", "Wind_gr"],
  "nrj-mobile": ["NRJ"],
  "o2": ["EPlus", "O2"],
  "odido": ["TMobile_nl", "Tele2_nl"],
  "oi": ["Oi"],
  "omantel": ["Omantel"],
  "one-albania": ["TMobile_al", "Vodafone_al"],
  "one-hungary": ["Vodafone_hu"],
  "one-montenegro": ["Telenor_me"],
  "one-nz": ["Vodafone_nz"],
  "ooredoo": ["Qtel"],
  "optimum": ["Altice"],
  "optus": ["Optus"],
  "ora": ["Ora"],
  "orange": ["Meditel", "Mobistar", "Orange", "VOX", "mobinil"],
  "paradise-mobile": ["Paradise"],
  "pc-mobile": ["PCMobile"],
  "pelephone": ["Pelephone"],
  "pepephone": ["Pepephone"],
  "personal": ["Personal"],
  "play": ["Play"],
  "plus": ["Polkomtel"],
  "pncc": ["PNCC"],
  "porto-seguro": ["PortoSeguro"],
  "post-luxembourg": ["LuxGSM"],
  "povo": ["Povo"],
  "primetel": ["PrimeTel"],
  "progresif": ["Progresif"],
  "proximus": ["Proximus"],
  "ptci": ["PTCI", "Panhandle"],
  "public-mobile": ["PublicMobile"],
  "puretalk": ["Puretalk"],
  "rain": ["Rain"],
  "rakuten-mobile": ["Rakuten"],
  "red-pocket": ["RedPocket"],
  "redtea-mobile": ["RedteaMobile"],
  "reliance-communications": ["Reliance"],
  "roamless": ["Roamless"],
  "robi": ["Robi"],
  "rogers": ["Cityfone", "Rogers"],
  "roshan": ["Roshan"],
  "safaricom": ["Safaricom"],
  "salam": ["SalamMobile"],
  "sasktel": ["Sasktel"],
  "sbermobile": ["Sberbank"],
  "seatel": ["Seatel"],
  "setar": ["Setar"],
  "sfr": ["SFR"],
  "shaw": ["Shaw"],
  "silknet": ["Telia_ge"],
  "silver-star": ["SilverStar"],
  "siminn": ["Siminn"],
  "simly": ["Simly"],
  "simple-mobile": ["Simple"],
  "singtel": ["SingTel"],
  "sk-telecom": ["SKT"],
  "skinny": ["Skinny"],
  "sky-mobile": ["Sky"],
  "smart-axiata": ["Smart_kh"],
  "smart-belize": ["Smart_bz"],
  "smart-ph": ["Smart_ph"],
  "smartfren": ["Smartfren"],
  "smartone": ["SmarTone"],
  "softbank": ["Softbank"],
  "soracom": ["Soracom"],
  "spark": ["Telecom"],
  "spark-celcomdigi": ["Yoodo"],
  "spectrum-mobile": ["Charter"],
  "srt": ["SRT"],
  "starhub": ["StarHub"],
  "stc": ["STC", "Viva"],
  "strata": ["Strata", "StrataNetwork"],
  "sun-mobile": ["SunMobile"],
  "sunrise": ["Sunrise", "UPC_ch"],
  "sure": ["Sure"],
  "swisscom": ["Swisscom"],
  "t-mobile": ["Sprint", "TMobile", "USCellular"],
  "t2": ["Tele2_ru"],
  "taiwan-mobile": ["TaiwanMobile", "Vibo"],
  "talkmobile": ["Talkmobile"],
  "tango": ["Tango"],
  "tashicell": ["TashiCell"],
  "tbaytel": ["Tbaytel"],
  "tcc-tonga": ["TCC"],
  "tcell": ["Telia_tj"],
  "tdc": ["TDC"],
  "team-telecom-armenia": ["VimpelCom_am"],
  "tele2": ["Tele2"],
  "telecom-namibia": ["TelecomNamibia"],
  "telekom-slovenije": ["Telekom", "TelekomSlovenije"],
  "telemach": ["Telemach"],
  "telenet": ["Telenet"],
  "telenor": ["Telenor"],
  "telesur": ["Telesur"],
  "telia": ["EMT", "NetCom", "NetworkNorway", "Omnitel", "Sonera", "Tele2_no", "Telia"],
  "telkom": ["8ta"],
  "telkomsel": ["Telkomsel"],
  "telstra": ["Telstra"],
  "telus": ["Telus"],
  "tesco-mobile": ["Tesco"],
  "three": ["Hutchison", "One"],
  "thumb-cellular": ["THC"],
  "tigo": ["Tigo"],
  "tim": ["TIM"],
  "timor-telecom": ["TimorTelecom"],
  "ting": ["Ting"],
  "tmcel": ["mcel"],
  "tracfone": ["TFW", "Tracfone"],
  "transatel": ["Transatel"],
  "true": ["True", "TrueH"],
  "tuenti": ["Tuenti"],
  "tunisie-telecom": ["Tuntel"],
  "tunz": ["DentWireless"],
  "turk-telekom": ["AVEA"],
  "turkcell": ["Turkcell"],
  "tusass": ["TELE"],
  "u-mobile": ["UMobile"],
  "umniah": ["Umniah"],
  "unefon": ["Unefon"],
  "union-wireless": ["UnionWireless"],
  "united-wireless": ["UnitedWireless"],
  "unitel-angola": ["Unitel_ao"],
  "unitel-laos": ["Unitel_la"],
  "unitel-mongolia": ["Unitel_mn"],
  "uq-mobile": ["UQ"],
  "uztelecom": ["UZTelecom"],
  "verizon": ["Verizon", "WCW"],
  "very-mobile": ["Very"],
  "vi": ["Idea", "Vodafone_in"],
  "viaero": ["Viaero"],
  "videotron": ["Videotron"],
  "viettel": ["Viettel"],
  "vinaphone": ["VinaPhone"],
  "vini": ["Vini"],
  "virgin": ["Virgin"],
  "virgin-plus": ["Bell_Virgin"],
  "visible": ["Visible"],
  "vivacom": ["Vivacom"],
  "vivo": ["vivo"],
  "vodafone": ["Vodafone"],
  "vodafone-cook-islands": ["TelecomCook"],
  "vtr": ["vtr"],
  "we-egypt": ["TelecomEgypt"],
  "wim": ["WIM"],
  "windtre": ["Wind"],
  "wingo": ["Wingo"],
  "wom": ["Avantel", "WOM"],
  "xfinity-mobile": ["Comcast"],
  "xl": ["XL"],
  "xplore": ["Xplornet"],
  "yas": ["Telma", "Tigo_tz"],
  "yes": ["Yes"],
  "yettel": ["Telenor_hu", "Telenor_rs"],
  "ymobile": ["YMobile"],
  "yoigo": ["Yoigo"],
  "yota": ["Yota"],
  "zain": ["Zain"],
  "zeop": ["Zeop"],
  "zet-mobile": ["VimpelCom_tj"],
  "zong": ["Zong"],
} as const satisfies Record<string, readonly string[]>;

/** Typed by the table, so asset() checks there is a file for every logo. */
export type LogoSlug = keyof typeof LOGOS;

const RULES = (Object.entries(LOGOS) as Array<[LogoSlug, readonly string[]]>).flatMap(([slug, words]) =>
  words.map((w) => ({ slug, words: w.split("_") })));

/** The logo slug for a bundle name, or undefined when no rule matches it. */
export function carrierLogo(name: string): LogoSlug | undefined {
  const words = name.split("_");
  let best: { slug: LogoSlug; length: number; at: number } | undefined;
  for (const r of RULES) {
    for (let at = 0; at + r.words.length <= words.length; at++) {
      if (!r.words.every((w, i) => words[at + i] === w)) continue;
      if (!best || r.words.length > best.length || (r.words.length === best.length && at > best.at)) {
        best = { slug: r.slug, length: r.words.length, at };
      }
    }
  }
  return best?.slug;
}
