/**
 * Regenerates packages/decode-android/src/fields.ts from AOSP release tags, which are immutable, so the output is reproducible.
 *   NODE_USE_ENV_PROXY=1 pnpm --filter @carrier-explode/android-fields generate [--out <file>]
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { base64ToBytes } from "@carrier-explode/binary";
import type { ConfigDoc } from "@carrier-explode/decode-android";
import { fetchWithRetry } from "@carrier-explode/http";
import { typeBySetter, typeBySuffix } from "./config-type.ts";
import { parseConfigSource, type KeyConstant } from "./java.ts";

const GITILES = "https://android.googlesource.com";

interface Source {
  readonly repo: string;
  readonly path: string;
}

const CCM = { repo: "platform/frameworks/base", path: "telephony/java/android/telephony/CarrierConfigManager.java" } as const satisfies Source;

/** Keys declared outside CarrierConfigManager, read at the newest release. */
const SERVICES = [
  { repo: "platform/packages/services/QualifiedNetworksService", path: "src/com/android/telephony/qns/QnsCarrierConfigManager.java" },
  { repo: "platform/packages/services/QualifiedNetworksService", path: "src/com/android/telephony/qns/QnsCarrierAnspSupportConfig.java" },
  { repo: "platform/packages/services/Iwlan", path: "src/com/google/android/iwlan/IwlanCarrierConfig.java" },
] as const satisfies readonly Source[];

const NEWEST_TAG = "android-17.0.0_r1";

/** Release tags and their API levels, oldest first. AOSP's main branches lag the releases, so only tags are read. */
const RELEASES = [
  ["android-10.0.0_r1", 29],
  ["android-11.0.0_r1", 30],
  ["android-12.0.0_r1", 31],
  ["android-12.1.0_r1", 32],
  ["android-13.0.0_r1", 33],
  ["android-14.0.0_r1", 34],
  ["android-15.0.0_r1", 35],
  ["android-16.0.0_r1", 36],
  [NEWEST_TAG, 37],
] as const satisfies ReadonlyArray<readonly [string, number]>;

const OLDEST_API = RELEASES[0][1];

async function fetchKeys(s: Source, tag: string): Promise<readonly KeyConstant[]> {
  const res = await fetchWithRetry(`${GITILES}/${s.repo}/+/refs/tags/${tag}/${s.path}?format=TEXT`);
  const parsed = parseConfigSource(new TextDecoder().decode(base64ToBytes((await res.text()).replace(/\s+/g, ""))));
  if (parsed.skipped.length) throw new Error(`unevaluable constants in ${s.path} at ${tag}:\n${parsed.skipped.join("\n")}`);
  process.stderr.write(`${tag} ${s.path}: ${parsed.keys.length} keys\n`);
  return parsed.keys;
}

/** One constant per key string; a renamed key keeps a deprecated alias, and the current name wins. */
function byKey(keys: readonly KeyConstant[]): Map<string, KeyConstant> {
  const out = new Map<string, KeyConstant>();
  for (const k of keys) {
    const seen = out.get(k.key);
    if (!seen || (seen.deprecated && !k.deprecated)) out.set(k.key, k);
  }
  return out;
}

/** Top-level CarrierConfigManager constants are shown bare, as the SDK docs do. */
const displayConstant = (constant: string): string => constant.replace(/^CarrierConfigManager\./, "");

function docOf(k: KeyConstant, since: number | undefined): ConfigDoc {
  const type = typeBySuffix(k.key) ?? (k.setter === undefined ? undefined : typeBySetter(k.setter));
  return {
    note: k.text,
    constant: displayConstant(k.constant),
    ...(type === undefined ? {} : { type }),
    ...(since === undefined ? {} : { since }),
    ...(k.deprecated ? { deprecated: true } : {}),
    ...(k.hidden ? { hidden: true } : {}),
    ...(k.default === undefined ? {} : { default: k.default }),
  };
}

function render(docs: ReadonlyArray<readonly [string, ConfigDoc]>): string {
  return [
    "/**",
    " * GENERATED by tools/android-fields/generate.ts; do not edit. Sources:",
    ` *   ${CCM.repo} ${CCM.path} at ${RELEASES.map(([tag]) => tag).join(", ")}`,
    ...SERVICES.map((s) => ` *   ${s.repo} ${s.path} at ${NEWEST_TAG}`),
    " * One entry per config key; ./docs.ts has the shape.",
    " */",
    "",
    'import type { ConfigDoc } from "./docs.ts";',
    "",
    "export const CONFIG_DOCS: Readonly<Record<string, ConfigDoc>> = {",
    ...docs.map(([key, doc]) => `  ${JSON.stringify(key)}: ${JSON.stringify(doc)},`),
    "};",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const { values } = parseArgs({ options: { out: { type: "string", default: fileURLToPath(new URL("../../packages/decode-android/src/fields.ts", import.meta.url)) } } });
  const releases: Array<{ readonly api: number; readonly keys: ReadonlyMap<string, KeyConstant> }> = [];
  for (const [tag, api] of RELEASES) releases.push({ api, keys: byKey(await fetchKeys(CCM, tag)) });
  const docs = new Map<string, ConfigDoc>();
  // A key's doc is its newest release's, and `since` its first; keys in the oldest tag may predate it, so get none.
  for (const { keys } of releases.toReversed()) {
    for (const [key, k] of keys) {
      if (docs.has(key)) continue;
      const since = releases.find((r) => r.keys.has(key))?.api ?? OLDEST_API;
      docs.set(key, docOf(k, since > OLDEST_API ? since : undefined));
    }
  }
  // Services' tags do not track SDK levels, so their keys get no `since`.
  for (const s of SERVICES) {
    for (const [key, k] of byKey(await fetchKeys(s, NEWEST_TAG))) if (!docs.has(key)) docs.set(key, docOf(k, undefined));
  }
  const sorted = [...docs].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  writeFileSync(values.out, render(sorted));
  process.stderr.write(`${sorted.length} keys -> ${values.out}\n`);
}

await main();
