-- MediaTek SBP ids whose OP-OTA names no PLMN, so no carrier's SIM rules select them, as MediaTek's own tables spell them;
-- and c4000, the Apple modem package of iPhone 16e (C1), iPhone Air and iPhone 17e (C1X).
INSERT INTO `labels` (`subject`, `code`, `field`, `value`, `origin`, `evidence`) VALUES
	('modem', 'c4000', 'name', 'Apple C1 and C1X', 'human', 'Firmware/c4000*/ftab.bin is the modem of iPhone17,5, iPhone18,4 and iPhone18,5 (BuildManifest); https://www.apple.com/newsroom/2025/02/apple-debuts-iphone-16e-a-powerful-new-member-of-the-iphone-16-family/ (C1), https://www.apple.com/newsroom/2025/09/introducing-iphone-air-a-powerful-new-iphone-with-a-breakthrough-design/ (C1X)'),
	('modem', 'SBP 20', 'name', 'Sprint', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 101', 'name', 'PCCW', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 103', 'name', 'SingTel', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 104', 'name', 'Starhub', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 105', 'name', 'AMX', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 106', 'name', '3HK', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 113', 'name', 'Beeline', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 116', 'name', 'U+', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 117', 'name', 'Smartfren', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 118', 'name', 'YTL', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 119', 'name', 'Natcom', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 121', 'name', 'Bell', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 126', 'name', 'Avea', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 128', 'name', 'DNA', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 131', 'name', 'TrueMove', 'human', 'UspServiceImpl.java sOperatorMapInfo, https://github.com/s1204IT/DchaLibraries-CT3'),
	('modem', 'SBP 137', 'name', 'Tele2', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 141', 'name', 'CELLC', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 143', 'name', 'Turkcell', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 150', 'name', 'Swisscom', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 152', 'name', 'Optus/Australia', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 153', 'name', 'VHA/Australia', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 161', 'name', 'Play', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 162', 'name', 'Freedom', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 163', 'name', 'Dialog', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 165', 'name', 'Sunrise', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 171', 'name', 'WOM/Chile', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 175', 'name', 'TDC', 'human', 'wod_optr.conf, https://github.com/SonyMTKDev'),
	('modem', 'SBP 178', 'name', 'SMART_CAMBODIA', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 179', 'name', 'Newroz', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 181', 'name', 'Telkom', 'human', 'wod_optr.conf, https://github.com/SonyMTKDev'),
	('modem', 'SBP 182', 'name', 'Proximus', 'human', 'wod_optr.conf, https://github.com/SonyMTKDev'),
	('modem', 'SBP 183', 'name', 'Personal_Argentina', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 185', 'name', '2degrees', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 189', 'name', 'UMOBILE', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 198', 'name', 'Sberbank', 'human', 'wod_optr.conf, https://github.com/goldfish07/cloud_upload'),
	('modem', 'SBP 267', 'name', 'ATT', 'human', 'Pixel 11 /etc/mdota/custom');
