/**
 * The index in D1: its tables, the writes of the index step and the feeds, and the typed reads pages and the API make,
 * some derived in SQL per request (countries, carrier modem configurations, rarity).
 */

export { indexDb, type IndexDb, type Page } from "./db.ts";
export {
	carrierCountries,
	carrierList,
	EVERY_CARRIER,
	carrierMembers,
	carrierModemConfigs,
	shippedModemConfigs,
	sourceModemConfigs,
	carrierOf,
	countryCarriers,
	countryList,
	countryOf,
	headIdentities,
	linkRules,
	writeLinked,
} from "./carriers.ts";
export type {
	CarrierFilter,
	CarrierModemConfig,
	HeadIdentity,
	ShippedModemConfig,
	ShownCarrier,
	ShownCountry,
} from "./carriers.ts";
export {
	deviceCoverage,
	deviceList,
	deviceOf,
	releasedDevices,
	setHas5g,
	statedDevices,
	statedSourceCounts,
	syncDevices,
	type ListedDevice,
	type ShownDevice,
} from "./devices.ts";
export { countFacts, lastFacts } from "./facts-written.ts";
export {
	CANDIDATE_SUBJECT,
	LABEL_CANDIDATE_KINDS,
	labelCandidates,
	syncLabels,
	writeLabelMiss,
	writeLabels,
	type LabelCandidate,
	type LabelCandidateKind,
} from "./labels.ts";
export {
	boardRadiosOf,
	headConcepts,
	configRadiosOf,
	missingProfiles,
	putProfiles,
	rareSettings,
	scanConcept,
	scanSetting,
	putBaseRows,
	selectedBy,
	syncHeadRows,
} from "./profiles.ts";
export { SCAN_HELD } from "./profiles.ts";
export type { Group, RareSetting, ScanHeld, ScannedSource } from "./profiles.ts";
export {
	changesOf,
	EVERY_RELEASE,
	heldRelease,
	modemConfigsOf,
	modemsOf,
	neighbours,
	newestReleaseDevices,
	putRelease,
	releaseIds,
	releaseList,
	releaseOf,
	changeFeed,
	feedKeySchema,
	shippedIn,
	releasesShipping,
	shippedSourceCount,
	syncChanges,
} from "./releases.ts";
export type {
	IndexedRelease,
	ListedRelease,
	ModemConfigRow,
	ModemFamily,
	ModemRow,
	NamedModemConfig,
	ReleaseFilter,
	FeedFilter,
	FeedItem,
	FeedKey,
	Shipped,
	ReleaseRows,
	ShownChange,
	ShownEnd,
} from "./releases.ts";
export {
	carrierSources,
	carrierStates,
	copiesOf,
	entriesOf,
	EVERY_SOURCE,
	featureStates,
	putOtaFile,
	putSource,
	platformRoutes,
	RULE_VIAS,
	routedBundles,
	rulesOnPlmn,
	SCANNED_STATES,
	sourceKeys,
	sourceList,
	sourceOf,
	statesOn,
	syncCopies,
	syncEntries,
	syncPhoneStates,
	syncRoutes,
} from "./sources.ts";
export type {
	FeatureFilter,
	FeatureRow,
	Holding,
	ListedSource,
	OrderedCopy,
	OtaFileRow,
	PhoneStatesRow,
	RoutedBundles,
	ScannedState,
	SimRuleRow,
	SourceFilter,
	SourceRow,
} from "./sources.ts";
