/** CarrierConfig key docs. The table (./fields.ts) is generated by tools/android-fields. */

import { CONFIG_DOCS } from "./fields.ts";

/** The value type a key's name promises (its `_bool`, `_int_array`... suffix, else its default's setter). */
export type ConfigType = "bool" | "int" | "long" | "double" | "string" | "int_array" | "long_array" | "bool_array" | "string_array" | "bundle";

export interface ConfigDoc {
  /** The javadoc's first paragraphs, plain text. Empty when AOSP has no javadoc for it. */
  readonly note: string;
  /** Java constant: `KEY_CARRIER_VOLTE_AVAILABLE_BOOL`, `Ims.KEY_SIP_TIMER_T1_MILLIS_INT`. */
  readonly constant: string;
  readonly type?: ConfigType;
  /** API level of the first release tag with the key; absent if it predates API 29. One past the newest tag means no release has it yet. */
  readonly since?: number;
  readonly deprecated?: boolean;
  /** `@hide`: not part of the public SDK. */
  readonly hidden?: boolean;
  /** AOSP's default, as Java literal text (`true`, `3000`, `["dun"]`), when it is a literal. */
  readonly default?: string;
}

/** Docs for one config key (nested-class keys include their prefix: `ims.sip_timer_t1_millis_int`). */
export function configDoc(key: string): ConfigDoc | undefined {
  return Object.hasOwn(CONFIG_DOCS, key) ? CONFIG_DOCS[key] : undefined;
}
