-- People's corrections, kept across the reset: SIM-linking rules and carrier names by source (from schema's links.ts),
-- and labels people wrote.
INSERT INTO `links` (`a`, `b`, `rule`, `why`) VALUES
	('ios:carrier:ATT_US', 'ios:carrier:ATT_NR_US', 'link', 'AT&T''s 5G SIMs (GID1 52/53) get their own iOS bundle'),
	('ios:carrier:ATT_aio_US', 'ios:carrier:ATT_aio_NR_US', 'link', 'Cricket''s 5G SIMs get their own iOS bundle'),
	('ios:carrier:KDDI_jp', 'ios:carrier:KDDI_NR_jp', 'link', 'au''s 5G network codes, split across two iOS bundles'),
	('ios:carrier:KDDI_LTE_jp', 'ios:carrier:KDDI_NR_jp', 'link', 'au''s LTE and 5G iOS bundles'),
	('ios:carrier:Verizon_Visible_LTE_US', 'ios:carrier:Verizon_Core_Visible_LTE_US', 'link', 'Visible on Verizon''s 5G core (GID2 1C) is still Visible'),
	('ios:carrier:Verizon_Visible_LTE_US', 'android:carrier:visible_us', 'link', 'iOS keys Visible by GID2 1A, Android by GID1 BAE1'),
	('ios:carrier:Verizon_Comcast_LTE_US', 'android:carrier:xfinity_us', 'link', 'Xfinity Mobile: iOS GID2 A3, Android GID1 BA0145'),
	('android:carrier:xfinity_us', 'android:carrier:xfinity2_us', 'link', 'both Android Xfinity Mobile profiles (GID1 BA0145, BA0164)'),
	('ios:carrier:Verizon_Charter_LTE_US', 'android:carrier:spectrum_us', 'link', 'Spectrum Mobile: iOS GID2 A7, Android GID1 BA0149'),
	('ios:carrier:Verizon_Cox_LTE_US', 'android:carrier:cox_us', 'link', 'Cox Mobile: iOS GID2 B1, Android by its own PLMN'),
	('ios:carrier:Verizon_TFW_LTE_US', 'android:carrier:tracfoneverizon_us', 'link', 'Tracfone on Verizon: iOS GID2 A1'),
	('ios:carrier:TMobile_MetroPCS_US', 'android:carrier:metropcs_us', 'link', 'Metro by T-Mobile: iOS GID1 6D, Android GID1 6D38'),
	('ios:carrier:O2_Giffgaff_UK', 'android:carrier:giffgaff_gb', 'link', 'giffgaff: iOS GID1 508F, Android GID1 50 or SPN'),
	('ios:carrier:O2_Sky_uk', 'android:carrier:sky_gb', 'link', 'Sky Mobile on O2'),
	('ios:carrier:Telus_ca', 'android:carrier:telus_ca', 'link', 'Android keys Telus by GID1 5455, iOS by plain network code'),
	('ios:carrier:Telus_Koodo_ca', 'android:carrier:koodo_ca', 'link', 'Koodo: Android GID1 4B4F'),
	('ios:carrier:Telus_PublicMobile_ca', 'android:carrier:publicmobile_ca', 'link', 'Public Mobile on Telus'),
	('ios:carrier:Vodafone_Lowi_es', 'android:carrier:lowi_es', 'link', 'Lowi on Vodafone Spain'),
	('ios:carrier:nTelos_LTE_US', 'android:carrier:docomopacific_us', 'split', 'both list 310470, but nTelos (Virginia) is not Docomo Pacific (Guam)'),
	('ios:carrier:KDDI_jp', 'android:carrier:kddimvno5gsa_jp', 'split', 'KDDI''s MVNOs share au''s 5G SA network code, but are not au'),
	('ios:carrier:KDDI_NR_jp', 'android:carrier:kddimvno5gsa_jp', 'split', 'KDDI''s MVNOs share au''s 5G SA network code, but are not au');
--> statement-breakpoint
INSERT INTO `labels` (`subject`, `code`, `field`, `value`, `origin`, `evidence`) VALUES
	('modem', 'Mav25', 'name', 'Qualcomm X80', 'human', NULL),
	('modem', 'Mav24', 'name', 'Qualcomm X71M', 'human', 'TechInsights'' iPhone 16 teardown found an SDX71M, not the X75 first reported.'),
	('modem', 'qualcomm', 'name', 'Qualcomm', 'human', NULL),
	('modem', 'shannon', 'name', 'Samsung Shannon', 'human', NULL),
	('modem', 'mediatek', 'name', 'MediaTek', 'human', NULL),
	('device', 'bluejay', 'released', '2022-04', 'human', 'https://source.android.com/docs/setup/reference/build-numbers (SD2A.220123.051.A3, security patch 2022-04-05)'),
	('device', 'sunfish', 'released', '2020-05', 'human', 'https://source.android.com/docs/setup/reference/build-numbers (QD4A.200317.027, security patch 2020-05-05)'),
	('source', 'android:carrier:ee_gb', 'carrierName', 'EE', 'human', NULL),
	('source', 'android:carrier:tmobile_nl', 'carrierName', 'Odido', 'human', NULL),
	('source', 'ios:carrier:Verizon_Visible_LTE_US', 'carrierName', 'Visible', 'human', NULL),
	('source', 'ios:carrier:Verizon_Comcast_LTE_US', 'carrierName', 'Xfinity Mobile', 'human', NULL),
	('source', 'ios:carrier:Verizon_Charter_LTE_US', 'carrierName', 'Spectrum Mobile', 'human', NULL),
	('source', 'ios:carrier:Verizon_Cox_LTE_US', 'carrierName', 'Cox Mobile', 'human', NULL),
	('source', 'ios:carrier:O2_Giffgaff_UK', 'carrierName', 'giffgaff', 'human', NULL),
	('source', 'ios:carrier:Telus_Koodo_ca', 'carrierName', 'Koodo', 'human', NULL),
	('source', 'ios:carrier:Telus_PublicMobile_ca', 'carrierName', 'Public Mobile', 'human', NULL),
	('source', 'ios:carrier:TMobile_UltraMint_US', 'carrierName', 'Mint Mobile and Ultra Mobile', 'human', NULL);
